Repository Amsterdam/vergunningcheck, pull requests merged in 2020-09, with the labels that each got.

#455 Bug: Usabilla exit polls
  ci/nginx-deployed.conf
Labels: bug

#458 Bug: EditButton on new line gives wrong style
  apps/client/src/atoms/EditButton.tsx
  apps/client/src/atoms/TextToEdit.tsx
  apps/client/src/atoms/index.js
  apps/client/src/components/QuestionAnswer.tsx
  apps/client/src/components/RegisterLookupSummary.js
Labels: bug

#457 Bug: <a> cannot appear as a descendant of <a>
  apps/client/src/pages/CheckerPage.js
Labels: bug

#456 Bug: postalCode undefined
  apps/client/src/components/Location/LocationInput.js
Labels: bug

#462 Updated STTR files
  apps/client/public/sttr/prod/dakkapel.json
  apps/client/public/sttr/prod/dakraam.json
  apps/client/public/sttr/prod/kozijn.json
  apps/client/public/sttr/prod/zonnepaneel.json
  apps/client/public/sttr/prod/zonwering.json
Labels: chore

#463 Feature: disabled Matomo and replaced all event trackers
  apps/client/src/components/Conclusion.js
  apps/client/src/components/Layouts/DefaultLayout.tsx
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Nav.js
  apps/client/src/hoc/withTracking.js
Labels: feature

#466 refactored matamo isActive
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Location/LocationResult.js
  apps/client/src/components/Questions.js
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/config/matomo.js
  apps/client/src/hoc/withTopic.js
  apps/client/src/pages/CheckerPage.js
Labels: feature

#473 Feat: Added Sentry tags for extra logging information
  apps/client/src/components/Questions.js
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/index.js
Labels: feature

#476 Matomo refactor and improvements
  apps/client/src/components/Conclusion.js
  apps/client/src/components/ContactSentence.tsx
  apps/client/src/components/Footer/Footer.js
  apps/client/src/components/Footer/Footer.test.js
  apps/client/src/components/Link.js
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Location/LocationResult.js
  apps/client/src/components/PhoneNumber.tsx
  apps/client/src/components/Questions.js
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/config/matomo.js
  apps/client/src/hoc/withTracking.js
  apps/client/src/intros/DakkapelIntro.js
  apps/client/src/intros/DakraamIntro.js
  apps/client/src/intros/KozijnenIntro.js
  apps/client/src/intros/ZonweringRolluikIntro.js
  apps/client/src/pages/CheckerPage.js
Labels: feature

#477 Feat: hide the print button on ie11
  apps/client/src/components/Conclusion.js
Labels: feature

#480 Hide DebugDecisionTable on print
  apps/client/src/pages/CheckerPage.js
Labels: feature

#482 Updated all @datapunt deps and fixed focus styles
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/components/HeaderStyles.ts
  apps/client/src/components/StepByStepNavigation/StepByStepItemStyle.ts
  apps/client/src/utils/themeUtils.ts
Labels: feature

#488 Implement text change
  apps/client/src/intros/DakkapelIntro.js
  apps/client/src/intros/DakraamIntro.js
  apps/client/src/intros/KozijnenIntro.js
  apps/client/src/intros/ZonweringRolluikIntro.js
Labels: chore

#487 Chore: show app version on DevHomePage
  apps/client/src/pages/DevHomePage.js
Labels: chore

#439 Feature: New Matomo event names + refactor
  apps/client/src/components/Conclusion.js
  apps/client/src/components/ContactSentence.tsx
  apps/client/src/components/Footer/Footer.js
  apps/client/src/components/Footer/Footer.test.js
  apps/client/src/components/Header.js
  apps/client/src/components/Link.js
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Location/LocationResult.js
  apps/client/src/components/Markdown/index.js
  apps/client/src/components/Markdown/renderers/LinkRenderer.tsx
  apps/client/src/components/Modal.js
  apps/client/src/components/Nav.js
  apps/client/src/components/PhoneNumber.tsx
  apps/client/src/components/Question.js
  apps/client/src/components/Questions.js
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/config/index.ts
  apps/client/src/config/matomo.js
  apps/client/src/hoc/withTopic.js
  apps/client/src/hoc/withTracking.js
  apps/client/src/intros/DakkapelIntro.js
  apps/client/src/intros/DakraamIntro.js
  apps/client/src/intros/KozijnenIntro.js
  apps/client/src/intros/ZonweringRolluikIntro.js
  apps/client/src/pages/CheckerPage.js
  apps/client/src/pages/IntroPage.js
  apps/graphql/package-lock.json
Labels: feature

#497 Updated lint-staged to prevent error
  apps/client/package.json
Labels: bug

#484 Make sure netlify does a clean install
  apps/client/package.json
  apps/graphql/package.json
Labels: chore

#498 Upgrade node-fetch and dot-prop dependencies
  package-lock.json
Labels: fix, security

#500 Replace old Footer props to remove deprecated logs
  apps/client/src/components/Footer/Footer.js
Labels: chore

#501 In case no active sections are found, reset the checker
  apps/client/src/pages/CheckerPage.js
Labels: bug

#496 Fixed broken STTR files
  apps/client/public/sttr/prod/dakkapel.json
  apps/client/public/sttr/prod/dakraam.json
  apps/client/public/sttr/prod/kozijn.json
  apps/client/public/sttr/prod/zonnepaneel.json
  apps/client/public/sttr/prod/zonwering.json
  apps/client/src/sttr_client/index.js
Labels: bug

#502 Replaced div with span to prevent warning
  apps/client/src/atoms/TextToEdit.tsx
Labels: bug

#506 Fixed OLO flow bug with resetChecker
  apps/client/src/pages/CheckerPage.js
Labels: bug

#504 Changed question button and scrolled to Conclusion
  apps/client/src/atoms/ScrollAnchor.tsx
  apps/client/src/atoms/index.js
  apps/client/src/components/ConclusionAlert.tsx
  apps/client/src/components/Question.js
  apps/client/src/components/Questions.js
  apps/client/src/utils/index.js
  apps/client/src/utils/index.test.js
Labels: feature

#485 Refactor nav to typescript
  apps/client/src/components/Nav.tsx
  apps/client/src/components/NavStyle.ts
Labels: chore

#510 Updated ASC-UI to fix bug in radio IE11
  apps/client/package-lock.json
  apps/client/package.json
Labels: dependencies

#511 Redirect to Intro in case no session context has been found
  apps/client/src/hoc/withChecker.js
  apps/client/src/pages/CheckerPage.js
Labels: bug

#503 Feat: Conclusion redesign
  apps/client/src/atoms/ComponentWrapper.ts
  apps/client/src/atoms/PrintButton.js
  apps/client/src/atoms/PrintButton.ts
  apps/client/src/components/Conclusion.js
  apps/client/src/components/Conclusion/ConclusionOutcome.test.js
  apps/client/src/components/Conclusion/ConclusionOutcome.tsx
  apps/client/src/components/Conclusion/NeedsPermit.tsx
  apps/client/src/components/Conclusion/NoPermitDescription.tsx
  apps/client/src/utils/test-ids.js
Labels: feature

#508 Added "go to another checker" functionality
  apps/client/src/components/Conclusion.js
  apps/client/src/components/Conclusion/ConclusionModal.test.js
  apps/client/src/components/Conclusion/ConclusionOutcome.tsx
  apps/client/src/components/Conclusion/NeedsPermit.tsx
  apps/client/src/components/Conclusion/NewCheckerModal.tsx
  apps/client/src/components/ConclusionAlert.tsx
  apps/client/src/components/Modal.js
  apps/client/src/components/Modal.test.js
  apps/client/src/components/Modal.tsx
  apps/client/src/components/ModalStyles.tsx
  apps/client/src/components/Question.js
  apps/client/src/config/matomo.js
  apps/client/src/context.tsx
  apps/client/src/hoc/withTopic.js
  apps/client/src/utils/test-ids.js
Labels: feature

#518 Refactored Answers and converted to TS
  apps/client/src/components/Answers.tsx
Labels: feature

#520 Added Label and give it more line-height
  apps/client/src/atoms/Label.js
  apps/client/src/atoms/index.js
  apps/client/src/components/Answers.tsx
  apps/client/src/components/Conclusion/NewCheckerModal.tsx
Labels: bug

#509 Enable npm audit (on graphql)
  apps/client/package-lock.json
  apps/graphql/package-lock.json
  apps/graphql/package.json
  apps/graphql/src/graphql/index.js
  ci/Dockerfile.client
  ci/Dockerfile.graphql
Labels: chore

#525 feat: Enable matamo trackevents
  apps/client/src/hoc/withTracking.js
Labels: feature

#527 Feedback on Conclusion PR
  apps/client/src/atoms/ScrollAnchor.tsx
  apps/client/src/components/Conclusion/ConclusionOutcome.test.js
  apps/client/src/components/Conclusion/NeedsPermit.tsx
  apps/client/src/components/Conclusion/NewCheckerModal.test.js
  apps/client/src/components/Conclusion/NewCheckerModal.tsx
  apps/client/src/components/Conclusion/NoPermitDescription.tsx
  apps/client/src/components/Nav.test.js
  apps/client/src/components/Questions.js
  apps/client/src/hoc/withTopic.js
  apps/client/src/hoc/withTracking.js
  apps/client/src/utils/index.js
  apps/client/src/utils/test-ids.js
Labels: chore

#526 Refactor how the Conclusion is rendered
  apps/client/src/components/Conclusion.js
  apps/client/src/components/Conclusion/ConclusionOutcome.test.js
  apps/client/src/components/Conclusion/ConclusionOutcome.tsx
  apps/client/src/components/Conclusion/NeedPermitContent.tsx
  apps/client/src/components/Conclusion/NeedPermitFooter.tsx
  apps/client/src/components/Conclusion/NewCheckerModal.tsx
  apps/client/src/components/Conclusion/NoPermitDescription.tsx
  apps/client/src/components/Conclusion/index.ts
  apps/client/src/utils/test-ids.js
Labels: feature

#528 Conclusion changes
  apps/client/src/atoms/List.ts
  apps/client/src/components/Conclusion.js
  apps/client/src/components/Conclusion/ConclusionOutcome.tsx
  apps/client/src/components/Conclusion/Disclaimer.tsx
  apps/client/src/components/Conclusion/NeedPermitContent.tsx
  apps/client/src/components/Conclusion/NeedPermitFooter.tsx
  apps/client/src/components/Conclusion/NewCheckerModal.tsx
  apps/client/src/components/Conclusion/NoPermitDescription.tsx
  apps/client/src/components/Conclusion/index.ts
Labels: feature

#531 Bugs and improvement in Print Styling
  apps/client/src/components/Conclusion.js
  apps/client/src/components/Conclusion/NeedPermitContent.tsx
  apps/client/src/components/Layouts/BaseLayoutStyles.js
  apps/client/src/utils/themeUtils.ts
Labels: bug

#533 Textual changes for error messages
  apps/client/src/components/Conclusion/NewCheckerModal.tsx
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Question.js
  apps/client/src/config/index.ts
Labels: feature

#537 Added unit tests
  apps/client/src/__mocks__/address.js
  apps/client/src/atoms/Alert.test.js
  apps/client/src/atoms/ComponentWrapper.test.js
  apps/client/src/atoms/EditButton.test.js
  apps/client/src/atoms/EditButton.tsx
  apps/client/src/atoms/List.test.js
  apps/client/src/atoms/PrintOnly.test.js
  apps/client/src/atoms/TextToEdit.test.js .test.js
  apps/client/src/atoms/TextToEdit.tsx
  apps/client/src/components/AddressLine.test.js
  apps/client/src/components/ContactSentence.test.js
  apps/client/src/components/Layouts/DefaultLayout.test.js
  apps/client/src/components/PrintDetails.test.js
  apps/client/src/components/QuestionAnswer.test.js
  apps/client/src/components/RegisterLookupSummary.test.js
  apps/client/src/utils/index.js
  apps/client/src/utils/test-ids.js
Labels: chore

#534 Feat: added matamo trackevent for conclusion
  apps/client/src/components/Conclusion/ConclusionOutcome.test.js
  apps/client/src/components/Conclusion/ConclusionOutcome.tsx
  apps/client/src/config/matomo.js
Labels: feature

#538 Feat: Created a url object in config
  apps/client/src/components/Conclusion/NeedPermitContent.tsx
  apps/client/src/components/Conclusion/NeedPermitFooter.tsx
  apps/client/src/config/index.ts
  apps/client/src/pages/RedirectPage.js
Labels: feature

#539 Updated buttons and margin between them
  apps/client/src/components/Conclusion/ConclusionOutcome.tsx
  apps/client/src/components/Conclusion/NeedPermitContent.tsx
  apps/client/src/components/Conclusion/NewCheckerModal.tsx
Labels: feature

#540 Feat: updated housenumber select with default value
  apps/client/src/components/Location/LocationFinder.js
Labels: feature

#522 The Conclusion redesign
  apps/client/src/__mocks__/addressMock.js
  apps/client/src/atoms/ComponentWrapper.ts
  apps/client/src/atoms/Label.js
  apps/client/src/atoms/List.ts
  apps/client/src/atoms/PrintButton.js
  apps/client/src/atoms/PrintButton.ts
  apps/client/src/atoms/ScrollAnchor.tsx
  apps/client/src/atoms/index.js
  apps/client/src/components/AddressLine.test.js
  apps/client/src/components/Answers.tsx
  apps/client/src/components/Conclusion.js
  apps/client/src/components/Conclusion/ConclusionOutcome.test.js
  apps/client/src/components/Conclusion/ConclusionOutcome.tsx
  apps/client/src/components/Conclusion/NeedPermitContent.tsx
  apps/client/src/components/Conclusion/NeedPermitFooter.tsx
  apps/client/src/components/Conclusion/NewCheckerModal.test.js
  apps/client/src/components/Conclusion/NewCheckerModal.tsx
  apps/client/src/components/Conclusion/NoPermitDescription.tsx
  apps/client/src/components/Conclusion/index.ts
  apps/client/src/components/ConclusionAlert.tsx
  apps/client/src/components/Disclaimer.test.js
  apps/client/src/components/Disclaimer.tsx
  apps/client/src/components/Layouts/BaseLayoutStyles.js
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Modal.js
  apps/client/src/components/Modal.test.js
  apps/client/src/components/Modal.tsx
  apps/client/src/components/ModalStyles.tsx
  apps/client/src/components/Nav.test.js
  apps/client/src/components/Question.js
  apps/client/src/components/Questions.js
  apps/client/src/components/RegisterLookupSummary.test.js
  apps/client/src/config/index.ts
  apps/client/src/config/matomo.js
  apps/client/src/context.tsx
  apps/client/src/hoc/withTopic.js
  apps/client/src/hoc/withTracking.js
  apps/client/src/pages/RedirectPage.js
  apps/client/src/utils/index.js
  apps/client/src/utils/index.test.js
  apps/client/src/utils/test-ids.js
  apps/client/src/utils/themeUtils.ts
Labels: feature

#524 Basic setup of e2e-testing with nightwatch and puppeteer
  apps/client/.gitignore
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/utils/test-ids.js
  apps/e2e/.gitignore
  apps/e2e/README.md
  apps/e2e/nightwatch.conf.js
  apps/e2e/nightwatch/config.js
  apps/e2e/nightwatch/tests/oloFlow.js
  apps/e2e/package-lock.json
  apps/e2e/package.json
  apps/e2e/puppeteer/tests/basic.ts
  apps/e2e/tsconfig.json
  ci/Dockerfile.client.dev
  ci/Dockerfile.dev
  ci/Dockerfile.e2e.dev
Labels: feature

#547 Replaced input fields
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/config/index.ts
Labels: feature

#548 Added files for a modal to change address
  apps/client/src/components/Conclusion/index.ts
  apps/client/src/components/Location/ChangeAddressModal.tsx
  apps/client/src/components/RegisterLookupSummary.js
Labels: feature

#554 Fixed Link with broken URL in Conclusion and fixed props
  apps/client/src/components/Conclusion/NeedPermitFooter.tsx
  apps/client/src/config/index.ts
Labels: bug

#555 Fixed another broken link
  apps/client/src/components/Conclusion/NeedPermitContent.tsx
Labels: bug

#550 Added basic test to Location
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/__mocks__/address.js
  apps/client/src/components/Location/LocationFinder.graphql
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Location/LocationFinder.test.js
Labels: chore
