Repository Amsterdam/vergunningcheck, pull requests merged in 2020-06, with the labels that each got.

#109 fix: Update last packages
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/index.js
  apps/graphql/package-lock.json
  apps/graphql/package.json
  package.json
Labels: internal

#120 feat: added a error on image
  apps/client/src/components/Visual.js
  apps/client/src/components/VisualStyles.js
Labels: enhancement

#137 Added the correct top margin to the figurecaption
  apps/client/src/components/Visual.js
  apps/client/src/components/VisualStyles.js
Labels: enhancement

#153 Improve eslint configuration, fix some warnings
  apps/client/package.json
  apps/client/src/components/Nav.test.js
  apps/client/src/routes.test.js
  apps/client/src/sttr_client/index.test.js
  apps/client/src/sttr_client/models/checker-flolegal.test.js
  apps/graphql/package.json
Labels: internal

#156 Create LICENSE
  LICENSE
Labels: documentation, enhancement

#101 Added browser refresh button support
  apps/client/src/__mocks__/context.js
  apps/client/src/components/DebugDecisionTable.js
  apps/client/src/components/Layouts/BaseLayout.tsx
  apps/client/src/components/Nav.js
  apps/client/src/components/Nav.test.js
  apps/client/src/components/QuestionAnswerTable.js
  apps/client/src/context.js
  apps/client/src/hoc/withAddress.js
  apps/client/src/hoc/withChecker.js
  apps/client/src/hoc/withTopic.js
  apps/client/src/index.js
  apps/client/src/pages/ConclusionPage.js
  apps/client/src/pages/LocationPage.js
  apps/client/src/pages/QuestionsPage.js
  apps/client/src/pages/ResultsPage.js
  apps/client/src/sttr_client/models/checker.js
  apps/client/src/sttr_client/models/checker.test.js
  apps/client/src/utils/index.js
  apps/client/src/utils/test-utils.js
Labels: enhancement

#100 Adding themeSpacing()
  apps/client/src/components/AddressResult.js
  apps/client/src/components/Modal.js
  apps/client/src/components/NavStyle.js
  apps/client/src/pages/AddressPageStyles.js
  apps/client/src/pages/LocationPageStyles.js
Labels: internal

#160 Implement fixes for new headers
  apps/graphql/src/secure.js
  ci/nginx-deployed.conf
Labels: internal, security

#152 Updated Matomo track events + refactor
  apps/client/src/MatomoConfig.js
  apps/client/src/components/Footer/Footer.js
  apps/client/src/components/Header.js
  apps/client/src/components/Layouts/DefaultLayout.tsx
  apps/client/src/components/Link.js
  apps/client/src/config.js
  apps/client/src/config.test.js
  apps/client/src/hoc/withTracking.js
  apps/client/src/index.js
  apps/client/src/pages/DevHomePage.js
  apps/client/src/utils/test-utils.js
Labels: internal

#162 Fixed the cursor with Links and fetched the correct context
  apps/client/src/components/HeaderStyles.js
  apps/client/src/components/Link.js
  apps/client/src/hoc/withTracking.js
Labels: bug

#159 Implement feedback
  apps/client/src/autofill.js
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/components/RegisterLookupSummaryStyles.js
  apps/client/src/hoc/withTopic.js
  apps/client/src/hoc/withTopic.test.js
  apps/client/src/pages/AddressPage.js
  apps/client/src/pages/ResultsPage.js
  apps/client/src/sttr_client/models/checker.js
Labels: documentation, internal

#142 Prettier import order
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/hoc/withAddress.js
Labels: enhancement

#172 Refactored files to typescript
  apps/client/src/config.ts
  apps/client/src/context.tsx
Labels: internal

#180 Feature/codecov GitHub action
  .github/workflows/default.yml
  README.md
  apps/client/package.json
  apps/graphql/.gitignore
  apps/graphql/package.json
  codecov.yml
  package.json
Labels: chore

#190 chore: Prepare size report with build script
  apps/client/package.json
  apps/client/scripts/rename.js
  package.json
Labels: chore

#182 chore: Added bundle size reporting on PRs
  .github/workflows/default.yml
Labels: chore

#197 release kozijnen
  apps/client/public/sttr/prod/kozijn.json
  apps/client/src/config.ts
  apps/client/src/intros/KozijnenIntroSTTR/index.js
Labels: feature

#179 feature: Added image group support
  apps/client/src/components/FormStyles.js
  apps/client/src/components/VisualStyles.js
Labels: feature

#196 feat: prevent submit when keyboard is open
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/pages/LocationPage.js
  apps/client/src/pages/LocationPage.test.js
Labels: feature

#207 fix: Remove stored answers after checker reset
  apps/client/src/hoc/withTopic.js
Labels: bug

#208 chore: Updated PR/commit badges
  .github/badge.yml
Labels: chore
