Repository Amsterdam/vergunningcheck, pull requests merged in 2020-11, with the labels that each got.

#660 TypeScripted Footer and Layout
  packages/client/src/components/Footer/Footer.test.tsx
  packages/client/src/components/Footer/Footer.tsx
  packages/client/src/components/Footer/FooterStyles.ts
  packages/client/src/components/Footer/index.ts
  packages/client/src/components/Layouts/BaseLayoutStyles.ts
  packages/client/src/components/Layouts/DefaultLayout.test.tsx
Labels: chore

#655 Typescript Functions refactor
  packages/client/src/components/AddressLines.tsx
  packages/client/src/components/Answers.tsx
  packages/client/src/components/AutoSuggestList.tsx
  packages/client/src/components/Conclusion.tsx
  packages/client/src/components/Conclusion/ConclusionOutcome.tsx
  packages/client/src/components/Conclusion/NeedPermitContent.tsx
  packages/client/src/components/Conclusion/NewCheckerModal.tsx
  packages/client/src/components/Error.tsx
  packages/client/src/components/Layouts/DefaultLayout.tsx
  packages/client/src/components/Location/EditLocationModal.tsx
  packages/client/src/components/Location/LocationFinder.tsx
  packages/client/src/components/Location/LocationInput.tsx
  packages/client/src/components/Location/LocationSummary.tsx
  packages/client/src/components/Modal.tsx
  packages/client/src/hoc/withTracking.tsx
  packages/client/src/pages/IntroPage.tsx
  packages/client/src/pages/olo/OloLocationInput.tsx
  packages/client/src/pages/olo/OloLocationResult.tsx
  packages/client/src/utils/index.ts
Labels: chore

#658 TypeScripted and tested Link and MarkDown
  packages/client/src/components/Link.js
  packages/client/src/components/Link.test.tsx
  packages/client/src/components/Link.tsx
  packages/client/src/components/Markdown/index.test.tsx
  packages/client/src/components/Markdown/index.tsx
  packages/client/src/components/Markdown/renderers/BlockRenderer.js
  packages/client/src/components/Markdown/renderers/BlockRenderer.tsx
  packages/client/src/components/Markdown/renderers/BlockRendererStyles.ts
  packages/client/src/components/Markdown/renderers/LinkRenderer.tsx
  packages/client/src/components/Markdown/renderers/ListRenderer.js
  packages/client/src/components/Markdown/renderers/ListRenderer.tsx
Labels: chore

#670 TypeScripted Questions + Question
  packages/client/package.json
  packages/client/src/__mocks__/context.js
  packages/client/src/components/Answers.tsx
  packages/client/src/components/Form.tsx
  packages/client/src/components/Question.tsx
  packages/client/src/components/QuestionAnswer.tsx
  packages/client/src/components/Questions.tsx
  packages/client/src/utils/index.ts
  packages/imtr-client/src/utils/index.ts
  packages/mocking/src/index.ts
Labels: chore

#672 Fixed inconsistencies: TS issues, docs and a URL cleaner
  CONTRIBUTING.md
  README.md
  packages/client/src/atoms/PrevButton.tsx
  packages/client/src/components/Error.tsx
  packages/client/src/components/Layouts/BaseLayout.tsx
  packages/client/src/components/Layouts/DefaultLayout.test.tsx
  packages/client/src/components/Layouts/DefaultLayout.tsx
  packages/client/src/components/Location/LocationFinder.tsx
  packages/client/src/components/Location/LocationSummary.tsx
  packages/client/src/components/Modal.tsx
  packages/client/src/components/PrintDetails.tsx
  packages/client/src/context.tsx
  packages/client/src/utils/index.test.js
  packages/client/src/utils/index.ts
Labels: chore

#667 feat: Implemented i18n-next poc
  packages/client/package-lock.json
  packages/client/package.json
  packages/client/src/components/Conclusion/NewCheckerModal.tsx
  packages/client/src/components/Location/LocationFinder.tsx
  packages/client/src/components/Location/LocationLoading.test.tsx
  packages/client/src/components/Location/LocationLoading.tsx
  packages/client/src/components/Location/LocationNotFound.test.tsx
  packages/client/src/components/Location/LocationNotFound.tsx
  packages/client/src/components/Question.tsx
  packages/client/src/config/index.ts
  packages/client/src/i18n/index.ts
  packages/client/src/i18n/nl.ts
  packages/client/src/index.js
  packages/client/src/intros/DakkapelIntro.tsx
  packages/client/src/intros/DakraamIntro.tsx
  packages/client/src/intros/KozijnenIntro.tsx
  packages/client/src/intros/ZonnepanelenIntro.tsx
  packages/client/src/intros/ZonweringRolluikIntro.tsx
  packages/client/src/intros/shared/Intro.test.tsx
  packages/client/src/intros/shared/Intro.tsx
  packages/client/src/utils/test-utils.js
Labels: feature

#661 Update Conclusion with Outcome and new Disclaimer
  packages/client/src/components/Conclusion.tsx
  packages/client/src/components/Conclusion/Conclusion.tsx
  packages/client/src/components/Conclusion/ConclusionOutcome.tsx
  packages/client/src/components/Conclusion/NeedPermitContent.tsx
  packages/client/src/components/Conclusion/NewCheckerModal.tsx
  packages/client/src/components/Conclusion/index.ts
  packages/client/src/components/ConclusionAlertStyles.ts
  packages/client/src/components/Disclaimer.test.js
  packages/client/src/components/Disclaimer.tsx
  packages/client/src/components/Location/EditLocationModal.tsx
  packages/client/src/components/Location/LocationInput.test.js
  packages/client/src/components/Question.tsx
  packages/client/src/components/QuestionAlert.test.tsx
  packages/client/src/components/QuestionAlert.tsx
  packages/client/src/components/QuestionAlertStyles.ts
  packages/client/src/components/QuestionAnswer.test.js
  packages/client/src/components/QuestionAnswer.tsx
  packages/client/src/components/Questions.tsx
  packages/client/src/i18n/nl.ts
  packages/client/src/pages/CheckerPage.js
  packages/client/src/routes.ts
  packages/client/src/utils/test-ids.js
  packages/e2e/nightwatch/tests/imtrFlow.js
  packages/imtr-client/src/models/checker.ts
  packages/imtr-client/src/models/permit.test.ts
  packages/imtr-client/src/types.ts
Labels: feature

#680 Add comment for sorting keys
  packages/imtr/src/parser.ts
Labels: chore

#681 Improve flow-types
  packages/client/src/config/index.ts
Labels: chore

#682 export getChecker as named function instead of default export
  packages/client/src/hoc/withChecker.tsx
  packages/imtr-client/index.ts
  packages/imtr-client/src/index.js
  packages/imtr-client/src/index.test.js
Labels: chore

#679 Update todo's and add a test
  ci/Dockerfile.client.dev
  packages/e2e/address.js
  packages/e2e/address.test.js
  packages/e2e/package-lock.json
  packages/e2e/package.json
Labels: chore

#687 Fixes the reload for the React hooks poc
  packages/client/src/SessionContext.tsx
Labels: bug

#685 Added Matomo events for `neighborhood` and `district`
  packages/client/src/__mocks__/address.ts
  packages/client/src/__mocks__/locationFinderGraphQLMocks.ts
  packages/client/src/components/Location/LocationFinder.graphql
  packages/client/src/components/Location/LocationFinder.test.js
  packages/client/src/components/Location/LocationFinder.tsx
  packages/client/src/components/Location/LocationInput.test.js
  packages/client/src/components/Location/LocationInput.tsx
  packages/client/src/components/Location/LocationNotFound.test.tsx
  packages/client/src/components/Location/LocationNotFound.tsx
  packages/client/src/config/matomo.js
  packages/client/src/i18n/nl.ts
  packages/client/src/pages/olo/OloLocationInput.test.js
  packages/graphql/src/graphql/address.js
  packages/graphql/src/graphql/area.js
  packages/graphql/src/graphql/index.js
  packages/graphql/src/loaders/bag/__snapshots__/accommodation.test.js.snap
  packages/graphql/src/loaders/bag/accommodation.js
Labels: feature

#701 Added the other intro text translations
  packages/client/src/intros/DakkapelIntro.test.tsx
  packages/client/src/intros/DakraamIntro.test.tsx
  packages/client/src/intros/KozijnenIntro.test.tsx
  packages/client/src/intros/ZonnepanelenIntro.test.tsx
  packages/client/src/intros/ZonweringRolluikIntro.test.tsx
Labels: chore

#700 Added text translations to intro.tests.tsx
  packages/client/src/intros/shared/Intro.test.tsx
Labels: chore

#709 Updated asc-ui and its components
  packages/client/package-lock.json
  packages/client/package.json
  packages/client/src/atoms/Alert.tsx
  packages/client/src/components/Error.tsx
  packages/client/src/components/Location/LocationFinder.tsx
  packages/client/src/components/Location/LocationNotFound.tsx
  packages/client/src/components/QuestionAlert.tsx
  packages/client/src/components/QuestionAlertStyles.ts
  packages/client/src/components/QuestionAnswer.test.tsx
  packages/client/src/components/QuestionAnswer.tsx
  packages/client/src/debug/DebugCheckersTable.tsx
Labels: feature

#702 Hooks > Fixes some bugs with resetting checker
  packages/client/src/CheckerContext.tsx
  packages/client/src/SessionContext.tsx
  packages/client/src/components/Conclusion/NewCheckerModal.tsx
  packages/client/src/components/Location/LocationInput.tsx
  packages/client/src/components/Location/LocationSummary.test.tsx
  packages/client/src/hooks/useChecker.ts
Labels: bug

#710 Fixed bug with Need-Report outcome for single checker
  packages/client/src/components/Conclusion/Conclusion.tsx
Labels: bug

#715 Fixed bug with multiple pageviews
  packages/client/src/components/Layouts/BaseLayout.tsx
  packages/client/src/components/Router.tsx
  packages/client/src/pages/LoadingPage.tsx
Labels: bug

#714 ClientOutcomes is more robust because it's converted to enum
  packages/client/src/components/Conclusion/Conclusion.tsx
  packages/client/src/components/Conclusion/ConclusionOutcome.tsx
  packages/client/src/components/Conclusion/content/PermitFree.tsx
  packages/client/src/components/Question.tsx
  packages/client/src/components/QuestionAlert.test.tsx
  packages/client/src/components/QuestionAlert.tsx
  packages/client/src/components/QuestionAnswer.test.js
  packages/client/src/components/QuestionAnswer.tsx
  packages/client/src/components/Questions.tsx
  packages/client/src/i18n/nl.ts
  packages/imtr-client/index.ts
  packages/imtr-client/src/models/checker.ts
  packages/imtr-client/src/models/permit.test.ts
  packages/imtr-client/src/types.ts
Labels: chore

#712 Added basic implementation of dynamic data-needs
  packages/client/src/SessionContext.tsx
  packages/client/src/components/Conclusion/NewCheckerModal.test.tsx
  packages/client/src/components/Conclusion/NewCheckerModal.tsx
  packages/client/src/components/Questions.tsx
  packages/client/src/pages/CheckerPage.tsx
  packages/client/src/pages/IntroPage.tsx
  packages/client/src/utils/test-ids.ts
Labels: feature

#699 Implement question ordering
  packages/client/public/imtr/transformed/2eYY7McaiRgfnERo9.json
  packages/client/public/imtr/transformed/37mYBbnidDABYfjiM.json
  packages/client/public/imtr/transformed/5CJrbgbWZP6uZsouY.json
  packages/client/public/imtr/transformed/6nb6FYuztEENADbmS.json
  packages/client/public/imtr/transformed/7vjj2nkFqxp8uQnqS.json
  packages/client/public/imtr/transformed/Aa2EX3YprpZQ65non.json
  packages/client/public/imtr/transformed/AkxinYRNNo679qi6T.json
  packages/client/public/imtr/transformed/BNH6kk2ePCLuqDLxi.json
  packages/client/public/imtr/transformed/BefWb33vB4BYGhN6R.json
  packages/client/public/imtr/transformed/D4mccynMtNdzYGhXF.json
  packages/client/public/imtr/transformed/LhnXDJZDmM7snACGX.json
  packages/client/public/imtr/transformed/MtNRm9GhSkdPavHJa.json
  packages/client/public/imtr/transformed/TRhZrFexMjBW42Ky6.json
  packages/client/public/imtr/transformed/TpPQq9NhKuTv4K6BQ.json
  packages/client/public/imtr/transformed/TuP6ido9xpJSSxjLi.json
  packages/client/public/imtr/transformed/WKPxKx4YBJ5fqYSni.json
  packages/client/public/imtr/transformed/WzTvyyRGkp2pf79aQ.json
  packages/client/public/imtr/transformed/X7LG33jf2M2Szav98.json
  packages/client/public/imtr/transformed/Xm2WwYeGkNN9w6rgQ.json
  packages/client/public/imtr/transformed/bmf5XsTrZpgTkbJoP.json
  packages/client/public/imtr/transformed/bouwwerk-slopen.json
  packages/client/public/imtr/transformed/bxBCdnrFZSbwxgmxC.json
  packages/client/public/imtr/transformed/dRy4PfDs7jQPc9gMG.json
  packages/client/public/imtr/transformed/dakkapel-plaatsen.json
  packages/client/public/imtr/transformed/dakraam-plaatsen.json
  packages/client/public/imtr/transformed/enavtgGrJEWwT5RGJ.json
  packages/client/public/imtr/transformed/hMwHKR7Wz4FP8Dm4x.json
  packages/client/public/imtr/transformed/kozijnen-plaatsen.json
  packages/client/public/imtr/transformed/mpQ4YsJWhRTzxkM8n.json
  packages/client/public/imtr/transformed/ngXhhpGtPN9LKqbdG.json
  packages/client/public/imtr/transformed/oeDaandaPbYNMgh4J.json
  packages/client/public/imtr/transformed/qPZnwcs4R4kYGEvnu.json
  packages/client/public/imtr/transformed/qPcaiw4H5vXkZgfFp.json
  packages/client/public/imtr/transformed/skPG9qqTqWyX9tSY7.json
  packages/client/public/imtr/transformed/yim42gLF6qjRXeD6D.json
  packages/client/public/imtr/transformed/zonnepanelen-of-zonneboiler-plaatsen.json
  packages/client/public/imtr/transformed/zonwering-of-rolluik-plaatsen.json
  packages/imtr-client/src/index.js
  packages/imtr/src/config.ts
  packages/imtr/src/parser.ts
  packages/imtr/src/transform.ts
Labels: feature
