Repository Amsterdam/vergunningcheck, pull requests merged in 2020-10, with the labels that each got.

#551 Updated the edit button for location and fixed the modal functionality
  apps/client/src/atoms/EditButton.tsx
  apps/client/src/components/Conclusion/NewCheckerModal.tsx
  apps/client/src/components/Location/ChangeAddressModal.tsx
  apps/client/src/components/Location/LocationResult.js
  apps/client/src/components/Modal.tsx
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/components/RegisterLookupSummary.test.js
Labels: feature

#556 feat: Result outcome changes
  apps/client/src/components/AddressLine.js
  apps/client/src/components/AddressLine.test.js
  apps/client/src/components/AddressLine.tsx
  apps/client/src/components/Conclusion/NewCheckerModal.tsx
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Location/LocationFinder.test.js
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Location/LocationResult.js
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/components/RegisterLookupSummary.test.js
  apps/client/src/pages/CheckerPage.js
Labels: feature

#561 Do not show back-button at the first question + Only store the address if the address has been found
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Question.js
Labels: bug

#558 Enabled the disabled test
  apps/client/src/__mocks__/addressMock.js
  apps/client/src/components/AddressLine.test.js
  apps/client/src/components/RegisterLookupSummary.test.js
Labels: feature

#562 Converted Form to TypeScript and added Test
  apps/client/src/components/Form.test.js
  apps/client/src/components/Form.tsx
  apps/client/src/components/FormStyles.ts
Labels: chore

#557 Added AutoSuggest and Debounce to LocationFinder
  apps/client/src/components/AddressLine.tsx
  apps/client/src/components/AutoSuggestList.js
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Location/LocationFinder.test.js
  apps/client/src/components/Location/LocationLoading.tsx
  apps/client/src/components/Location/LocationNotFound.tsx
  apps/client/src/hooks/useDebounce.ts
Labels: feature

#560 Fix console warnings and leave the OLO flow the same
  apps/client/src/__mocks__/addressMockNoMonument.js
  apps/client/src/components/AddressLine.tsx
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/components/RegisterLookupSummary.test.js
Labels: bug

#475 Move intro pages to dynamic intro
  apps/client/src/intros/DakkapelIntro.js
  apps/client/src/intros/DakraamIntro.js
  apps/client/src/intros/KozijnenIntro.js
  apps/client/src/intros/ZonnepanelenIntro.js
  apps/client/src/intros/ZonweringRolluikIntro.js
  apps/client/src/intros/shared/Intro.tsx
  apps/client/src/intros/shared/IntroHeading.tsx
  apps/client/src/intros/shared/IntroSituationDescription.tsx
  apps/client/src/intros/shared/index.js
Labels: feature

#571 AutoSuggest improvements on focusing, fetching and displaying errors
  apps/client/src/components/AutoSuggestList.js
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Location/LocationFinder.test.js
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Location/LocationNotFound.tsx
  apps/client/src/utils/index.js
  apps/client/src/utils/index.test.js
Labels: feature

#569 feat: changed multiple sentences
  apps/client/src/components/AddressLines.test.js
  apps/client/src/components/AddressLines.tsx
  apps/client/src/components/Location/ChangeAddressModal.tsx
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Nav.test.js
  apps/client/src/components/Nav.tsx
  apps/client/src/components/NavStyle.ts
  apps/client/src/components/RegisterLookupSummary.js
Labels: feature

#572 Fix/change address modal
  apps/client/src/components/AddressLines.tsx
  apps/client/src/components/RegisterLookupSummary.js
Labels: bug, fix

#573 Disables the native browser auto-suggest
  apps/client/src/components/Location/LocationFinder.js
Labels: feature

#574 Fixed the edit address button and refactored lots of code
  apps/client/src/atoms/EditButton.test.js
  apps/client/src/atoms/FormTitle.tsx
  apps/client/src/atoms/index.js
  apps/client/src/components/AddressLines.test.js
  apps/client/src/components/AddressLines.tsx
  apps/client/src/components/Layouts/BaseLayout.tsx
  apps/client/src/components/Question.js
  apps/client/src/components/RegisterLookupSummary.js
Labels: feature

#575 Updated @amsterdam ASC dependencies
  CONTRIBUTING.md
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/atoms/Alert.tsx
  apps/client/src/atoms/ComponentWrapper.ts
  apps/client/src/atoms/EditButton.tsx
  apps/client/src/atoms/FormTitle.tsx
  apps/client/src/atoms/Label.js
  apps/client/src/atoms/List.ts
  apps/client/src/atoms/ListItem.js
  apps/client/src/atoms/OrderedList.js
  apps/client/src/atoms/PrevButton.tsx
  apps/client/src/atoms/PrintButton.ts
  apps/client/src/atoms/PrintOnly.tsx
  apps/client/src/atoms/TextToEdit.tsx
  apps/client/src/components/Answers.tsx
  apps/client/src/components/Conclusion.tsx
  apps/client/src/components/Conclusion/ConclusionOutcome.tsx
  apps/client/src/components/Conclusion/NeedPermitContent.tsx
  apps/client/src/components/Conclusion/NeedPermitFooter.tsx
  apps/client/src/components/Conclusion/NewCheckerModal.tsx
  apps/client/src/components/Conclusion/NoPermitDescription.tsx
  apps/client/src/components/ConclusionAlert.tsx
  apps/client/src/components/ConclusionAlertStyles.ts
  apps/client/src/components/Disclaimer.tsx
  apps/client/src/components/Footer/Footer.js
  apps/client/src/components/Footer/FooterStyles.js
  apps/client/src/components/HeaderStyles.ts
  apps/client/src/components/Layouts/BaseLayout.tsx
  apps/client/src/components/Layouts/BaseLayoutStyles.js
  apps/client/src/components/Link.js
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Location/LocationResult.js
  apps/client/src/components/Markdown/renderers/BlockRendererStyles.js
  apps/client/src/components/Modal.tsx
  apps/client/src/components/ModalStyles.tsx
  apps/client/src/components/Nav.tsx
  apps/client/src/components/NavStyle.ts
  apps/client/src/components/PrintDetails.js
  apps/client/src/components/QuestionAnswer.tsx
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/components/StepByStepNavigation/StepByStepItem.tsx
  apps/client/src/components/StepByStepNavigation/StepByStepItemStyle.ts
  apps/client/src/components/StepByStepNavigation/StepByStepNavigation.test.tsx
  apps/client/src/components/StepByStepNavigation/StepByStepNavigation.tsx
  apps/client/src/components/StepByStepNavigation/StepByStepNavigationStyle.ts
  apps/client/src/components/StepByStepNavigation/StepByStepTitle.tsx
  apps/client/src/components/VisualStyles.js
  apps/client/src/index.js
  apps/client/src/intros/shared/DefaultOloIntro.js
  apps/client/src/intros/shared/Intro.tsx
  apps/client/src/pages/NotFoundPage.js
  apps/client/src/pages/RedirectPage.js
  apps/client/src/pages/StepperPage.jsx
  apps/client/src/utils/test-utils.js
Labels: feature

#577 Converted LocationInput to TypeScript
  apps/client/src/components/Location/LocationResult.tsx
  apps/client/src/components/RegisterLookupSummary.js
Labels: feature

#580 Fixed bug in debouncing LocationNotFound by moving it to LocationFinder
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Location/LocationFinder.test.js
  apps/client/src/components/Location/LocationNotFound.tsx
Labels: feature

#581 RegisterLookupSummary now is TypeScript
  apps/client/src/atoms/ComponentWrapper.ts
  apps/client/src/components/RegisterLookupSummary.tsx
Labels: feature

#578 Fixed bugs by making app backwards compatible
  apps/client/src/pages/CheckerPage.js
Labels: bug

#579 Added Matomo events and resetChecker functionality to the Change Address Modal
  apps/client/src/components/Location/ChangeAddressModal.test.js
  apps/client/src/components/Location/ChangeAddressModal.tsx
  apps/client/src/components/RegisterLookupSummary.tsx
  apps/client/src/config/matomo.js
  apps/client/src/context.tsx
  apps/client/src/pages/CheckerPage.js
Labels: feature

#582 Typescript and tests improvements
  apps/client/src/atoms/ComponentWrapper.ts
  apps/client/src/components/AddressLines.test.js
  apps/client/src/components/ConclusionAlert.tsx
  apps/client/src/components/ConclusionAlertStyles.ts
  apps/client/src/components/Form.tsx
  apps/client/src/components/HiddenDebugInfo.js
  apps/client/src/components/Layouts/BaseLayout.tsx
  apps/client/src/components/Layouts/DefaultLayout.test.js
  apps/client/src/components/Location/LocationResult.tsx
  apps/client/src/components/Nav.test.js
  apps/client/src/components/Question.js
  apps/client/src/components/QuestionAnswer.tsx
  apps/client/src/components/RegisterLookupSummary.tsx
  apps/client/src/pages/StepperPage.jsx
  apps/client/src/utils/passPropsToChildren.ts
Labels: chore

#584 Updated Matomo events for the Modals
  apps/client/src/components/Conclusion/NewCheckerModal.test.js
  apps/client/src/components/Conclusion/NewCheckerModal.tsx
  apps/client/src/components/Location/ChangeAddressModal.test.js
  apps/client/src/components/Location/ChangeAddressModal.tsx
  apps/client/src/config/matomo.js
Labels: feature

#583 fixed location results test
  apps/client/src/components/Location/LocationResult.test.js
  apps/client/src/components/Location/LocationResult.tsx
Labels: chore

#585 Renamed ChangeAddressModal to EditLocation
  apps/client/src/components/Conclusion/ConclusionOutcome.test.js
  apps/client/src/components/Location/EditLocation.test.js
  apps/client/src/components/Location/EditLocation.tsx
  apps/client/src/components/RegisterLookupSummary.tsx
Labels: feature

#587 Updated location styling and fixed several location bugs
  apps/client/src/atoms/ComponentWrapper.ts
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/RegisterLookupSummary.tsx
Labels: bug

#586 LocationInput converted to typescript
  apps/client/src/components/Error.tsx
  apps/client/src/components/Location/LocationInput.tsx
Labels: chore

#590 Small design implementation for the DevHomePage
  apps/client/src/pages/DevHomePage.js
Labels: chore

#576 Implement cityScape scopes
  apps/client/public/imtr/transformed/37mYBbnidDABYfjiM.json
  apps/client/public/imtr/transformed/5CJrbgbWZP6uZsouY.json
  apps/client/public/imtr/transformed/6nb6FYuztEENADbmS.json
  apps/client/public/imtr/transformed/7vjj2nkFqxp8uQnqS.json
  apps/client/public/imtr/transformed/Aa2EX3YprpZQ65non.json
  apps/client/public/imtr/transformed/AkxinYRNNo679qi6T.json
  apps/client/public/imtr/transformed/LhnXDJZDmM7snACGX.json
  apps/client/public/imtr/transformed/MtNRm9GhSkdPavHJa.json
  apps/client/public/imtr/transformed/TRhZrFexMjBW42Ky6.json
  apps/client/public/imtr/transformed/TuP6ido9xpJSSxjLi.json
  apps/client/public/imtr/transformed/WKPxKx4YBJ5fqYSni.json
  apps/client/public/imtr/transformed/WzTvyyRGkp2pf79aQ.json
  apps/client/public/imtr/transformed/X7LG33jf2M2Szav98.json
  apps/client/public/imtr/transformed/Xm2WwYeGkNN9w6rgQ.json
  apps/client/public/imtr/transformed/bmf5XsTrZpgTkbJoP.json
  apps/client/public/imtr/transformed/dRy4PfDs7jQPc9gMG.json
  apps/client/public/imtr/transformed/dakkapel-plaatsen.json
  apps/client/public/imtr/transformed/dakraam-plaatsen.json
  apps/client/public/imtr/transformed/enavtgGrJEWwT5RGJ.json
  apps/client/public/imtr/transformed/hMwHKR7Wz4FP8Dm4x.json
  apps/client/public/imtr/transformed/kozijnen-plaatsen.json
  apps/client/public/imtr/transformed/mpQ4YsJWhRTzxkM8n.json
  apps/client/public/imtr/transformed/ngXhhpGtPN9LKqbdG.json
  apps/client/public/imtr/transformed/oeDaandaPbYNMgh4J.json
  apps/client/public/imtr/transformed/qPcaiw4H5vXkZgfFp.json
  apps/client/public/imtr/transformed/skPG9qqTqWyX9tSY7.json
  apps/client/public/imtr/transformed/yim42gLF6qjRXeD6D.json
  apps/client/public/imtr/transformed/zonnepanelen-of-zonneboiler-plaatsen.json
  apps/client/public/imtr/transformed/zonwering-of-rolluik-plaatsen.json
  apps/client/src/__mocks__/address.ts
  apps/client/src/__mocks__/addressMock.ts
  apps/client/src/__mocks__/addressMockNoCityScape.ts
  apps/client/src/__mocks__/addressMockNoMonument.ts
  apps/client/src/components/Location/LocationFinder.graphql
  apps/client/src/components/Location/LocationResult.test.js
  apps/client/src/components/RegisterLookupSummary.test.js
  apps/client/src/components/RegisterLookupSummary.tsx
  apps/client/src/config/autofill.js
  apps/client/src/imtr_client/models/checker.js
  apps/graphql/config/default.js
  apps/graphql/fixtures/addressProperties.js
  apps/graphql/src/graphql/cityScape.js
  apps/graphql/src/graphql/monument.js
  apps/graphql/src/graphql/restriction.js
  apps/graphql/src/loaders/_limitation/index.js
  apps/graphql/src/loaders/cityScape/__mocks__/1477.json
  apps/graphql/src/loaders/cityScape/__snapshots__/cityScape.test.js.snap
  apps/graphql/src/loaders/cityScape/cityScape.test.js
  apps/graphql/src/loaders/cityScape/index.js
  apps/graphql/src/loaders/geoSearch/index.js
  apps/graphql/src/loaders/monument/monument.js
  apps/imtr/src/transform.ts
Labels: feature

#591 Reset the autoSuggestValue on each key press to prevent bugs
  apps/client/src/components/Location/LocationFinder.js
Labels: bug

#592 Location e2e test
  apps/e2e/README.md
  apps/e2e/build/.gitkeep
  apps/e2e/package-lock.json
  apps/e2e/package.json
  apps/e2e/puppeteer/config.ts
  apps/e2e/puppeteer/tests/basic.ts
  apps/e2e/puppeteer/tests/location-component.ts
  apps/e2e/puppeteer/types.ts
  apps/e2e/puppeteer/util.ts
Labels: feature

#593 Fix broken e2e tests
  apps/client/src/components/Location/LocationFinder.js
  apps/e2e/nightwatch/tests/oloFlow.js
Labels: bug

#594 Updated loading text by replacing the title
  apps/client/src/components/Location/LocationLoading.tsx
Labels: feature

#596 LocationFinder to typescript
  apps/client/src/components/AutoSuggestList.tsx
  apps/client/src/components/Location/LocationFinder.tsx
  apps/client/src/components/RegisterLookupSummary.tsx
Labels: chore

#595 Fixed bug when showing result that wasn't a true exactMatch
  apps/client/src/components/Location/LocationFinder.tsx
  apps/client/src/utils/index.js
Labels: bug

#602 Refactored some utils (added `isValidPostalcode` and tests)
  apps/client/src/components/Location/LocationFinder.tsx
  apps/client/src/utils/index.js
  apps/client/src/utils/index.test.js
Labels: feature

#605 Debug table git info
  apps/client/.env
  apps/client/package.json
  apps/client/src/components/Layouts/BaseLayout.tsx
  ci/Dockerfile.client
Labels: feature

#606 Removed EditButton from OLO and renamed EditLocationModal
  apps/client/src/components/Location/EditLocation.tsx
  apps/client/src/components/Location/EditLocationModal.test.tsx
  apps/client/src/components/Location/EditLocationModal.tsx
  apps/client/src/components/Location/LocationFinder.test.js
  apps/client/src/components/RegisterLookupSummary.test.js
  apps/client/src/components/RegisterLookupSummary.tsx
Labels: feature

#604 General location component refactors
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/atoms/Alert.test.js
  apps/client/src/atoms/ComponentWrapper.test.js
  apps/client/src/atoms/List.test.js
  apps/client/src/atoms/PrintOnly.test.js
  apps/client/src/atoms/TextToEdit.test.js
  apps/client/src/components/Answers.test.js
  apps/client/src/components/Conclusion/NewCheckerModal.test.js
  apps/client/src/components/Conclusion/NewCheckerModal.tsx
  apps/client/src/components/ContactSentence.test.js
  apps/client/src/components/Disclaimer.test.js
  apps/client/src/components/Location/EditLocationModal.tsx
  apps/client/src/components/Location/LocationFinder.tsx
  apps/client/src/components/Location/LocationLoading.test.tsx
  apps/client/src/components/Location/LocationNotFound.test.tsx
  apps/client/src/components/Location/LocationResult.test.js
  apps/client/src/components/Location/LocationResult.tsx
  apps/client/src/components/Modal.test.js
  apps/client/src/components/Nav.test.js
  apps/client/src/components/Nav.tsx
  apps/client/src/components/NavStyle.ts
  apps/client/src/components/PrintDetails.test.js
  apps/client/src/components/QuestionAnswer.test.js
  apps/client/src/components/RegisterLookupSummary.test.js
  apps/client/src/components/RegisterLookupSummary.tsx
  apps/client/src/components/StepByStepNavigation/StepByStepNavigation.test.tsx
  apps/client/src/config/index.test.js
  apps/client/src/routes.test.js
Labels: feature

#603 Converted utils to TypeScript and refactored
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/utils/index.test.js
  apps/client/src/utils/index.ts
  apps/e2e/package-lock.json
Labels: feature

#609 Gray bullet bug on CheckerPage
  apps/client/src/components/Location/LocationInput.tsx
Labels: bug

#608 Debug Table are TS-ed and in Accordion
  apps/client/src/components/DebugDecisionTable.js
  apps/client/src/components/DebugDecisionTable.tsx
  apps/client/src/components/HiddenDebugInfo.js
  apps/client/src/components/HiddenDebugInfo.tsx
  apps/client/src/components/HiddenDebugInfoStyles.ts
  apps/client/src/context.tsx
Labels: feature

#611 Fixed titles, styling and tests for RegistryLookupSummary
  apps/client/src/__mocks__/addressMockNoRestrictions.ts
  apps/client/src/atoms/List.ts
  apps/client/src/components/Location/LocationFinder.tsx
  apps/client/src/components/Location/LocationResult.tsx
  apps/client/src/components/RegisterLookupSummary.test.js
  apps/client/src/components/RegisterLookupSummary.tsx
  apps/client/src/pages/CheckerPage.js
  apps/client/src/utils/test-ids.js
Labels: feature

#612 Fixed bug in resetting state
  apps/client/src/pages/CheckerPage.js
Labels: bug

#613 Fixed bug displaying the Location Summary
  apps/client/src/__mocks__/addressMockNoZoningplans.ts
  apps/client/src/components/RegisterLookupSummary.test.js
  apps/client/src/components/RegisterLookupSummary.tsx
Labels: bug

#614 Added matomo events for GraphQL errors and Restrictions
  apps/client/src/components/Location/LocationFinder.tsx
  apps/client/src/components/Location/LocationInput.tsx
  apps/client/src/config/matomo.js
Labels: feature

#616 Wrapped (new) Debug Variables in Accordion
  ci/Dockerfile.client
  packages/client/.env
  packages/client/src/components/DebugDecisionTable.tsx
  packages/client/src/components/DebugVariables.tsx
  packages/client/src/components/HiddenDebugInfo.tsx
  packages/client/src/components/HiddenDebugInfoStyles.ts
  packages/client/src/components/Layouts/BaseLayout.tsx
Labels: feature

#618 Fixed e2e for multiple addresses on multiple flows
  .github/workflows/default.yml
  packages/e2e/puppeteer/config.ts
  packages/e2e/puppeteer/tests/location-component.ts
  packages/e2e/puppeteer/types.ts
  packages/mocking/src/restriction.ts
Labels: chore

#626 Textual changes to the OLO Flow
  packages/client/src/components/Location/LocationSummary.test.js
  packages/client/src/components/Location/LocationSummary.tsx
  packages/client/src/intros/shared/DefaultOloIntro.js
  packages/client/src/pages/olo/OloLocationResult.test.js
  packages/client/src/pages/olo/OloLocationResult.tsx
Labels: feature

#630 Skip the intro page on the OLO flow
  packages/client/src/components/Location/LocationInput.tsx
  packages/client/src/pages/IntroPage.tsx
  packages/e2e/nightwatch/tests/oloFlow.js
Labels: feature

#627 Added extra conclusion information for `need permit`
  packages/client/src/atoms/ComponentWrapper.ts
  packages/client/src/components/Conclusion.tsx
  packages/client/src/components/Conclusion/ConclusionOutcome.test.js
  packages/client/src/components/Conclusion/ConclusionOutcome.tsx
  packages/client/src/components/Conclusion/NeedPermitContent.tsx
  packages/client/src/components/Conclusion/NeedPermitFooter.tsx
  packages/client/src/components/Conclusion/index.ts
  packages/client/src/config/index.ts
  packages/client/src/config/matomo.js
Labels: feature

#632 OLO flow textual changes
  packages/client/src/pages/olo/OloLocationResult.tsx
Labels: feature

#625 Upgrade react to v16.14
  packages/client/package-lock.json
  packages/client/package.json
Labels: chore

#634 Disable autoFocus when `postalCode` has been found
  packages/client/src/components/Location/LocationFinder.tsx
Labels: bug

#635 Textual and styling changes after the test
  packages/client/src/components/Conclusion/NeedPermitContent.tsx
  packages/client/src/config/index.ts
  packages/client/src/pages/olo/OloLocationResult.test.js
  packages/client/src/pages/olo/OloLocationResult.tsx
Labels: feature

#639 Removed old OLO Intro files and added tests
  packages/client/src/config/index.ts
  packages/client/src/intros/AanbouwIntro.js
  packages/client/src/intros/BouwwerkSlopenIntro.js
  packages/client/src/intros/DakkapelIntro.test.tsx
  packages/client/src/intros/DakkapelIntro.tsx
  packages/client/src/intros/DakraamIntro.test.tsx
  packages/client/src/intros/DakraamIntro.tsx
  packages/client/src/intros/InternVerbouwenIntro.js
  packages/client/src/intros/KozijnenIntro.test.tsx
  packages/client/src/intros/KozijnenIntro.tsx
  packages/client/src/intros/ZonnepanelenIntro.test.tsx
  packages/client/src/intros/ZonnepanelenIntro.tsx
  packages/client/src/intros/ZonweringRolluikIntro.test.tsx
  packages/client/src/intros/ZonweringRolluikIntro.tsx
  packages/client/src/intros/shared/DefaultOloIntro.js
  packages/client/src/intros/shared/index.js
Labels: feature

#640 Adjusted the link in the Conclusion component
  packages/client/src/components/Conclusion/NeedPermitContent.tsx
  packages/client/src/config/index.ts
Labels: feature

#637 OLO flow bug when going directly to Location Results component
  packages/client/src/pages/olo/OloLocationResult.tsx
Labels: bug

#641 Upgraded components and added tests
  packages/client/src/components/Loading.test.tsx
  packages/client/src/components/Loading.tsx
  packages/client/src/components/PrintDetails.tsx
  packages/client/src/components/ScrollToTop.test.tsx
  packages/client/src/components/ScrollToTop.tsx
  packages/client/src/components/Visual.test.tsx
  packages/client/src/components/Visual.tsx
  packages/client/src/components/VisualStyles.test.tsx
  packages/client/src/components/VisualStyles.ts
  packages/client/src/utils/test-ids.js
Labels: feature

#638 Added e2e tests and refactored the e2e config
  packages/client/src/atoms/EditButton.tsx
  packages/client/src/components/Answers.tsx
  packages/client/src/components/Location/EditLocationModal.tsx
  packages/client/src/components/Question.js
  packages/client/src/utils/test-ids.js
  packages/e2e/address.js
  packages/e2e/host.js
  packages/e2e/nightwatch/config.js
  packages/e2e/nightwatch/tests/imtrFlow.js
  packages/e2e/nightwatch/tests/oloFlow.js
  packages/e2e/puppeteer/config.ts
  packages/e2e/puppeteer/tests/basic.ts
  packages/e2e/puppeteer/tests/location-component.ts
  packages/e2e/selectors.js
  packages/mocking/src/address.ts
  packages/mocking/src/index.ts
Labels: feature

#649 Refactored Location components and fixed the tests
  packages/client/src/__mocks__/locationFinderGraphQLMocks.ts
  packages/client/src/components/AutoSuggestList.tsx
  packages/client/src/components/Form.tsx
  packages/client/src/components/Location/LocationFinder.test.js
  packages/client/src/components/Location/LocationInput.test.js
  packages/client/src/components/Location/LocationInput.tsx
  packages/client/src/components/Location/LocationNotFound.tsx
  packages/client/src/pages/CheckerPage.js
  packages/client/src/pages/olo/OloLocationInput.tsx
  packages/client/src/pages/olo/OloLocationResult.tsx
  packages/client/src/utils/test-ids.js
Labels: feature

#651 Added new Titles and refactored some pages
  packages/client/src/components/DebugVariables.tsx
  packages/client/src/components/Layouts/BaseLayout.tsx
  packages/client/src/components/Layouts/DefaultLayout.test.js
  packages/client/src/components/Layouts/DefaultLayout.tsx
  packages/client/src/config/index.ts
  packages/client/src/pages/CheckerPage.js
  packages/client/src/pages/DevHomePage.js
  packages/client/src/pages/DevHomePage.tsx
  packages/client/src/pages/IntroPage.tsx
  packages/client/src/pages/RedirectPage.tsx
  packages/client/src/pages/StepperPage.jsx
  packages/client/src/pages/olo/OloLocationInput.tsx
  packages/client/src/pages/olo/OloLocationResult.tsx
Labels: feature

#657 TypeScripted all atoms and atoms tests
  packages/client/src/atoms/Alert.test.tsx
  packages/client/src/atoms/ComponentWrapper.test.tsx
  packages/client/src/atoms/EditButton.test.tsx
  packages/client/src/atoms/HideForPrint.ts
  packages/client/src/atoms/Label.ts
  packages/client/src/atoms/List.test.tsx
  packages/client/src/atoms/ListItem.ts
  packages/client/src/atoms/OrderedList.ts
  packages/client/src/atoms/PrintButton.test.tsx
  packages/client/src/atoms/PrintButton.ts
  packages/client/src/atoms/PrintOnly.test.tsx
  packages/client/src/atoms/TextToEdit.test.tsx
  packages/client/src/atoms/index.ts
Labels: chore

#659 Updated client packages
  packages/client/package-lock.json
  packages/client/package.json
Labels: chore
