Repository Amsterdam/vergunningcheck, pull requests merged in 2020-07, with the labels that each got.

#214 Chore: added npm install to build:size-report script
  apps/client/package.json
Labels: chore

#213 Make bundle size smaller (replaced uniqBy and updated react-hook-form)
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/components/QuestionAnswerTable.js
  apps/client/src/pages/LocationPage.js
  apps/client/src/utils/index.js
Labels: chore

#218 Setup boilerplate for chappie 2.0
  apps/client/src/checker/Stepper.js
  apps/client/src/checker/Wrapper.js
  apps/client/src/pages/StepperPage.js
  apps/client/src/pages/WrapperPage.js
  apps/client/src/routes.js
Labels: chore

#223 Bug: fixed default export with graphqlHTTP
  apps/graphql/src/graphql/index.js
Labels: bug

#226 Add prestart script to install deps
  apps/client/package.json
  apps/graphql/package.json
Labels: feature

#229 Improve Boolean answer order (yes/no)
  apps/client/src/components/Question.js
Labels: feature

#127 Autofill questions
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/public/sttr/prod/dakkapel.json
  apps/client/public/sttr/prod/dakraam.json
  apps/client/public/sttr/prod/kozijn.json
  apps/client/public/sttr/prod/zonnepaneel.json
  apps/client/src/__mocks__/context.js
  apps/client/src/components/AddressData.js
  apps/client/src/components/AddressLine.js
  apps/client/src/components/AddressResult.js
  apps/client/src/components/AddressResultStyles.js
  apps/client/src/components/DebugDecisionTable.js
  apps/client/src/components/Header.js
  apps/client/src/components/Link.js
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Question.js
  apps/client/src/components/Router.js
  apps/client/src/config/autofill.js
  apps/client/src/config/index.test.js
  apps/client/src/config/index.ts
  apps/client/src/config/matomo.js
  apps/client/src/context.tsx
  apps/client/src/hoc/withAddress.js
  apps/client/src/hoc/withAutofillData.js
  apps/client/src/hoc/withChecker.js
  apps/client/src/hoc/withConclusion.js
  apps/client/src/hoc/withOloRedirect.js
  apps/client/src/hoc/withTopic.js
  apps/client/src/hoc/withTopic.test.js
  apps/client/src/index.js
  apps/client/src/pages/AddressPage.js
  apps/client/src/pages/ConclusionPage.js
  apps/client/src/pages/DevHomePage.js
  apps/client/src/pages/IntroPage.js
  apps/client/src/pages/LoadingPage.js
  apps/client/src/pages/LocationPage.js
  apps/client/src/pages/LocationPage.test.js
  apps/client/src/pages/LocationPageStyles.js
  apps/client/src/pages/QuestionsPage.js
  apps/client/src/pages/QuestionsPage.test.js
  apps/client/src/pages/RedirectPage.js
  apps/client/src/pages/ResultsPage.js
  apps/client/src/routes.js
  apps/client/src/sttr_client/index.js
  apps/client/src/sttr_client/models/checker.js
  apps/client/src/sttr_client/models/checker.test.js
  apps/client/src/sttr_client/models/permit.test.js
  apps/client/src/sttr_client/models/question.js
  apps/client/src/sttr_client/utils/mocks.js
  apps/client/src/utils/index.js
  apps/client/src/utils/test-utils.js
  apps/client/sttr_build/parser.js
  apps/graphql/config/development.js
Labels: feature

#144 Netlify (including Autofill)
  .gitignore
  apps/client/package.json
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/components/RegisterLookupSummaryStyles.js
  apps/client/src/config/autofill.js
  apps/client/src/hoc/withTopic.test.js
  apps/client/src/intros/KozijnenIntroSTTR/index.js
  apps/client/src/intros/KozijnenIntroTest.js
  apps/client/src/pages/AddressPage.js
  apps/client/src/pages/ConclusionPage.js
  apps/client/src/pages/ResultsPage.js
  apps/client/src/sttr_client/models/checker.js
  apps/graphql/.gitignore
  apps/graphql/app.js
  apps/graphql/config/.env
  apps/graphql/config/.env.development
  apps/graphql/config/development.js
  apps/graphql/config/index.js
  apps/graphql/config/netlify.js
  apps/graphql/config/netlify_develop.js
  apps/graphql/config/production.js
  apps/graphql/config/test.js
  apps/graphql/graphql.js
  apps/graphql/package-lock.json
  apps/graphql/package.json
  apps/graphql/server.js
  apps/graphql/src/graphql/index.js
  apps/graphql/src/loaders/bag/accommodation.js
  apps/graphql/src/loaders/bag/berth.js
  apps/graphql/src/loaders/bag/building.js
  apps/graphql/src/loaders/bagSearch/index.js
  apps/graphql/src/loaders/geoSearch/index.js
  apps/graphql/src/loaders/monument/monument.js
  apps/graphql/src/loaders/monument/situation.js
  apps/graphql/src/loaders/zoningPlan/index.js
  apps/graphql/src/secure.js
  apps/graphql/src/util.js
  netlify.toml
  package.json
Labels: feature

#237 bug: Fix olo flow after autofill
  apps/client/src/config/autofill.js
Labels: bug

#210 Added Sentry to monitor errors and security
  README.md
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/components/Visual.js
  apps/client/src/config/sentry.ts
  apps/client/src/index.js
  ci/nginx-deployed.conf
Labels: feature

#230 Add address fixtures for testing
  apps/graphql/fixtures/addressProperties.js
  apps/graphql/fixtures/addressSearch.js
Labels: feature

#238 Fix several bugs
  apps/client/src/__mocks__/context.js
  apps/client/src/components/DebugDecisionTable.js
  apps/client/src/config/autofill.js
  apps/client/src/context.tsx
  apps/client/src/hoc/withAutofillData.js
  apps/client/src/hoc/withChecker.js
  apps/client/src/hoc/withTopic.js
  apps/client/src/pages/ConclusionPage.js
  apps/client/src/pages/LocationPage.js
  apps/client/src/pages/QuestionsPage.js
  apps/client/src/pages/ResultsPage.js
Labels: bug

#250 fix: remove legacy lru_map dependency
  apps/graphql/package-lock.json
  apps/graphql/package.json
Labels: dependencies, fix

#249 fix: Remove legacy lru-cache dependency
  apps/graphql/package-lock.json
  apps/graphql/package.json
Labels: bug, dependencies, fix

#251 Remove quotes util function
  apps/client/src/components/Answers.js
  apps/client/src/components/QuestionAnswerTable.js
  apps/client/src/utils/index.js
Labels: fix

#252 Fix sttr-flow without address page
  apps/client/src/components/DebugDecisionTable.js
  apps/client/src/pages/QuestionsPage.js
Labels: bug

#259 Fix: autofill after refresh
  apps/client/src/hoc/withChecker.js
Labels: bug

#262 Remove zoning-plan texts where not applicable
  apps/client/src/config/index.ts
  apps/client/src/intros/AanbouwIntro.js
  apps/client/src/intros/BouwwerkSlopenIntro.js
  apps/client/src/intros/DakkapelIntro.js
  apps/client/src/intros/DakraamIntro.js
  apps/client/src/intros/InternVerbouwenIntro.js
  apps/client/src/intros/KozijnenIntro.js
  apps/client/src/intros/KozijnenIntroSTTR/StyledKozijnenIntroSTTR.js
  apps/client/src/intros/KozijnenIntroSTTR/illustration.png
  apps/client/src/intros/KozijnenIntroSTTR/index.js
  apps/client/src/intros/ZonnepanelenIntro.js
  apps/client/src/intros/shared/DefaultOloIntro.js
  apps/client/src/intros/shared/LocationIntro.js
Labels: feature

#224 Feature: added step by step navigation
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/checker/Stepper.js
  apps/client/src/components/Layouts/BaseLayout.tsx
  apps/client/src/components/Nav.js
  apps/client/src/components/NavStyle.js
  apps/client/src/components/QuestionAnswerTable.js
  apps/client/src/components/StepByStepNavigation/StepByStepItem.tsx
  apps/client/src/components/StepByStepNavigation/StepByStepItemStyle.ts
  apps/client/src/components/StepByStepNavigation/StepByStepNavigation.test.tsx
  apps/client/src/components/StepByStepNavigation/StepByStepNavigation.tsx
  apps/client/src/components/StepByStepNavigation/StepByStepNavigationStyle.ts
  apps/client/src/components/StepByStepNavigation/StepByStepTitle.tsx
  apps/client/src/components/StepByStepNavigation/index.ts
  apps/client/src/hoc/withChecker.js
  apps/client/src/pages/StepperPage.js
  apps/client/src/pages/StepperPage.jsx
  apps/client/src/routes.js
  apps/client/src/utils/test-ids.js
  apps/client/src/utils/usePassPropsToChildren.ts
Labels: feature

#236 chore: Create dependabot.yml
  .github/dependabot.yml
Labels: chore

#288 Fix: Select kept firing empty onChange events making the form unable to submit
  apps/client/src/components/Location/LocationFinder.js
Labels: bug

#290 Revert "Bump react-scripts from 3.4.0 to 3.4.1"
  apps/client/package-lock.json
  apps/client/package.json
Labels: bug

#291 Updated @apollo/react-hooks and @apollo/react-testing to 4.0.0
  apps/client/package-lock.json
  apps/client/package.json
Labels: dependencies

#278 Fix back-back-forward bug, add DDTable for easier debuggin
  apps/client/src/components/DebugDecisionTable.js
  apps/client/src/pages/AddressPage.js
  apps/client/src/pages/ConclusionPage.js
  apps/client/src/pages/IntroPage.js
  apps/client/src/pages/LocationPage.test.js
  apps/client/src/pages/QuestionsPage.js
  apps/client/src/sttr_client/models/checker.js
Labels: bug

#296 Fix: Removed unneccesary chappie2.0 files
  apps/client/src/checker/Stepper.js
  apps/client/src/checker/Wrapper.js
  apps/client/src/pages/StepperPage.js
  apps/client/src/pages/WrapperPage.js
  apps/client/src/routes.js
Labels: bug

#297 Small feedback fixes
  apps/client/src/config/autofill.js
  apps/client/src/sttr_client/models/checker.js
  apps/client/src/sttr_client/models/checker.test.js
  apps/client/src/utils/index.js
  apps/graphql/config/netlify_develop.js
Labels: fix

#293 Fix: using Memo to stop rerendering Header+Footer
  apps/client/src/components/Footer/Footer.js
  apps/client/src/components/Header.js
Labels: bug

#318 Feature: Added step by step navigation WCAG (and refactored)
  apps/client/src/components/StepByStepNavigation/StepByStepItem.tsx
  apps/client/src/components/StepByStepNavigation/StepByStepItemStyle.ts
  apps/client/src/components/StepByStepNavigation/StepByStepNavigation.tsx
  apps/client/src/pages/StepperPage.jsx
Labels: feature

#317 Bug: show caption even though image loading fails
  apps/client/src/components/Visual.js
Labels: bug

#302 Feat: Basic stepper component with states
  apps/client/src/components/Conclusion.js
  apps/client/src/components/Location/Location.js
  apps/client/src/components/Question.js
  apps/client/src/components/QuestionAnswerTable.js
  apps/client/src/components/QuestionAnswerTableStyles.js
  apps/client/src/components/Questions.js
  apps/client/src/config/autofill.js
  apps/client/src/pages/AddressPage.js
  apps/client/src/pages/ConclusionPage.js
  apps/client/src/pages/LocationPage.test.js
  apps/client/src/pages/QuestionsPage.js
  apps/client/src/pages/QuestionsPage.test.js
  apps/client/src/pages/ResultsPage.js
  apps/client/src/pages/WrapperPage.js
  apps/client/src/routes.js
  apps/client/src/utils/usePassPropsToChildren.ts
Labels: feature

#316 Chore: Step by step navigation > Fixed tests 100%
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/components/StepByStepNavigation/StepByStepItem.tsx
  apps/client/src/components/StepByStepNavigation/StepByStepNavigation.test.tsx
Labels: chore

#329 Feat: Chappie2.0 progress
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/components/AddressLine.js
  apps/client/src/components/Conclusion.js
  apps/client/src/components/Location/Location.js
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Questions.js
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/components/RegisterLookupSummaryStyles.js
  apps/client/src/config/autofill.js
  apps/client/src/context.tsx
  apps/client/src/hoc/withChecker.js
  apps/client/src/hoc/withTopic.js
  apps/client/src/pages/IntroPage.js
  apps/client/src/pages/WrapperPage.js
Labels: feature

#331 Bug fix: IE11 styling issue
  apps/client/src/components/FormStyles.js
Labels: bug

#330 Feature: Added zonwering STTR and Intro
  apps/client/public/sttr/prod/zonwering.json
  apps/client/src/config/index.ts
  apps/client/src/intros/ZonweringRolluikIntro.js
  apps/client/src/static/media/Uitleg_Luik.png
  apps/client/src/static/media/Uitleg_Markies.png
  apps/client/src/static/media/Uitleg_Rolluik.png
  apps/client/src/static/media/Uitleg_Uitvalrol.png
  apps/client/sttr_build/config.js
Labels: feature

#332 Feature: Added full-width background to Stepper
  .github/badge.yml
  apps/client/src/components/Layouts/BaseLayoutStyles.js
  apps/client/src/components/NavStyle.js
  apps/client/src/components/StepByStepNavigation/StepByStepItem.tsx
  apps/client/src/components/StepByStepNavigation/StepByStepItemStyle.ts
  apps/client/src/components/StepByStepNavigation/StepByStepNavigation.test.tsx
Labels: feature

#335 Feature: Updated layout (mobile, Location and OLO)
  apps/client/src/components/HeaderStyles.js
  apps/client/src/components/Layouts/BaseLayout.tsx
  apps/client/src/components/Layouts/BaseLayoutStyles.js
  apps/client/src/components/Location/Location.js
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/components/StepByStepNavigation/StepByStepItemStyle.ts
  apps/client/src/components/StepByStepNavigation/StepByStepNavigationStyle.ts
  apps/client/src/config/index.ts
  apps/client/src/pages/WrapperPage.js
Labels: feature
