Repository Amsterdam/vergunningcheck, pull requests merged in 2020-08, with the labels that each got.

#337 Feat: chappie2.0 reinit checker after location change, and keep question until answer change
  apps/client/src/components/Location/Location.js
  apps/client/src/components/Question.js
  apps/client/src/components/Questions.js
  apps/client/src/hoc/withChecker.js
  apps/client/src/pages/WrapperPage.js
Labels: feature

#344 Bug: Hide unanswered questions + browser refresh bugs + refactor
  apps/client/src/components/Answers.js
  apps/client/src/components/Question.js
  apps/client/src/components/Questions.js
Labels: bug

#345 Feat: Add lines between StepByStepNavigation Items
  apps/client/src/components/Questions.js
  apps/client/src/components/StepByStepNavigation/StepByStepNavigationStyle.ts
  apps/client/src/pages/WrapperPage.js
Labels: feature

#333 Feat: State with active & finished
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Location/LocationResult.js
  apps/client/src/components/Questions.js
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/hoc/withChecker.js
  apps/client/src/hoc/withTopic.js
  apps/client/src/pages/IntroPage.js
  apps/client/src/pages/WrapperPage.js
  apps/client/src/utils/test-ids.js
Labels: feature

#351 Chore: Fixed test for Answers.js
  apps/client/src/components/Answers.test.js
Labels: chore

#348 Chore: Refactor the checker.stack.map() function
  apps/client/src/components/Questions.js
  apps/client/src/pages/WrapperPage.js
Labels: chore

#352 Feature: Added titles to Olo Flow and refactored the Olo Url
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Location/LocationResult.js
  apps/client/src/config/index.ts
  apps/client/src/pages/RedirectPage.js
  apps/client/src/pages/WrapperPage.js
Labels: feature

#349 Update dot-prop
  package-lock.json
Labels: security

#363 Bug: Helmet no longer supports `true` as a middleware option.
  apps/graphql/src/secure.js
Labels: bug

#367 Feature: Updated NGINX config to fix bugs with Sentry and Usabilla
  ci/nginx-deployed.conf
Labels: feature

#365 Temporary disabled the OLO flow for the Zonwering checker
  apps/client/src/config/index.ts
  apps/client/src/intros/ZonweringRolluikIntroOlo.js
Labels: feature

#368 Docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs

#383 Feat: Re-added the Prev button in Form Navigation
  apps/client/src/components/Location/LocationResult.js
  apps/client/src/components/Question.js
  apps/client/src/components/Questions.js
  apps/client/src/pages/WrapperPage.js
Labels: feature

#379 Feature: show alert is question needs permit
  apps/client/src/components/Question.js
  apps/client/src/components/QuestionNeedsPermit.js
  apps/client/src/components/Questions.js
  apps/client/src/sttr_client/models/checker.js
Labels: feature

#384 chore: Renamed WrapperPage to CheckerPage
  apps/client/src/components/StepByStepNavigation/StepByStepNavigation.test.tsx
  apps/client/src/config/autofill.js
  apps/client/src/pages/CheckerPage.js
  apps/client/src/pages/IntroPage.js
  apps/client/src/routes.js
Labels: chore

#385 Feat: Print styling + Refactored QuestionAnswer
  apps/client/src/components/Conclusion.js
  apps/client/src/components/HeaderStyles.js
  apps/client/src/components/Layouts/BaseLayoutStyles.js
  apps/client/src/components/QuestionAnswer.tsx
  apps/client/src/components/QuestionAnswerStyles.ts
  apps/client/src/components/Questions.js
  apps/client/src/components/StepByStepNavigation/StepByStepItemStyle.ts
Labels: feature

#386 Feat: Refactored PermitAlert and changed color to Yellow
  apps/client/src/components/PermitAlert.tsx
  apps/client/src/components/PermitAlertStyles.ts
  apps/client/src/components/Question.js
  apps/client/src/components/QuestionAnswer.tsx
  apps/client/src/components/QuestionNeedsPermit.js
Labels: feature

#387 Bug: Sentry warning of `substring` undefined
  apps/client/src/components/Location/LocationInput.js
Labels: bug

#388 Bug: Show correct conclusion text with Contact conclusion
  apps/client/src/components/Conclusion.js
Labels: bug

#353 Feature: ApolloClient v3
  README.md
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/apolloClient.js
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/index.js
  apps/client/src/utils/test-utils.js
Labels: feature

#389 Feat: Fixed flow when Conclusion is displayed, but it shouldn't
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Location/LocationResult.js
  apps/client/src/components/Questions.js
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/pages/CheckerPage.js
Labels: feature

#390 Feature: Chappie2.0 bug fixes and refactor
  apps/client/src/atoms/Alert.js
  apps/client/src/atoms/EditButton.tsx
  apps/client/src/atoms/EditButtonStyle.ts
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Location/LocationResult.js
  apps/client/src/components/QuestionAnswer.tsx
  apps/client/src/components/Questions.js
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/pages/CheckerPage.js
Labels: feature

#391 Chore: Refactor the onQuestionNext to goToQuestion()
  apps/client/src/components/Questions.js
  apps/client/src/pages/CheckerPage.js
Labels: chore

#392 Bug: removed duplicate state change
  apps/client/src/hoc/withTopic.js
Labels: bug

#395 Bug: fixed issue with undefined string
  apps/client/src/utils/index.js
Labels: bug

#394 Feature: Show and skip already answered questions
  apps/client/src/components/QuestionAnswer.tsx
  apps/client/src/components/Questions.js
  apps/client/src/pages/CheckerPage.js
Labels: feature

#404 Feat: Set Conclusion section to active if it needs to be active
  apps/client/src/components/StepByStepNavigation/StepByStepItem.tsx
  apps/client/src/pages/CheckerPage.js
Labels: feature

#402 Feature: Added ConclusionAlert for Contact Conclusion
  apps/client/src/components/ConclusionAlert.tsx
  apps/client/src/components/ConclusionAlertStyles.ts
  apps/client/src/components/PermitAlert.tsx
  apps/client/src/components/Question.js
  apps/client/src/components/QuestionAnswer.tsx
  apps/client/src/components/Questions.js
Labels: feature

#407 Bug: Removed whitespace by changing quotes
  apps/client/src/components/ConclusionAlert.tsx
Labels: bug

#406 Bug: Fixed unnecessary line between StepItems
  apps/client/src/pages/CheckerPage.js
Labels: bug

#294 STTR versioning
  apps/client/public/sttr/prod/dakkapel.json
  apps/client/public/sttr/prod/dakraam.json
  apps/client/public/sttr/prod/kozijn.json
  apps/client/public/sttr/prod/zonnepaneel.json
  apps/client/public/sttr/prod/zonwering.json
  apps/client/src/components/DebugDecisionTable.js
  apps/client/src/sttr_client/index.js
  apps/client/src/sttr_client/models/checker-flolegal.test.js
  apps/client/src/sttr_client/models/checker.test.js
  apps/client/src/sttr_client/models/permit.js
  apps/client/src/sttr_client/models/permit.test.js
  apps/client/sttr_build/index.js
  apps/graphql/package.json
Labels: feature

#408 Bug: OLO Flow had issues with routing to CheckerPage
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Nav.js
  apps/client/src/hoc/withChecker.js
  apps/client/src/hoc/withTopic.js
  apps/client/src/pages/CheckerPage.js
Labels: bug

#409 Bug: Only be able to go to Conclusion when Questions are finished
  apps/client/src/pages/CheckerPage.js
Labels: bug

#405 Feat: Added the disabled styling of the edit button
  apps/client/src/atoms/EditButton.tsx
  apps/client/src/atoms/EditButtonStyle.ts
  apps/client/src/components/QuestionAnswer.tsx
  apps/client/src/components/Questions.js
Labels: feature

#410 Feat: Zonwering updates from UX-test
  apps/client/public/sttr/prod/zonwering.json
  apps/client/src/intros/ZonweringRolluikIntro.js
  apps/client/src/static/media/Uitleg_Luik.png
  apps/client/src/static/media/Uitleg_Markies.png
  apps/client/src/static/media/Uitleg_Rolluik.png
  apps/client/src/static/media/Uitleg_Uitvalrol.png
Labels: feature

#417 Feature: Updated the margin above the Footer
  apps/client/src/components/Layouts/BaseLayoutStyles.js
  apps/client/src/components/Nav.js
  apps/client/src/components/NavStyle.js
  apps/client/src/components/Question.js
  apps/client/src/pages/CheckerPage.js
  apps/client/src/pages/IntroPage.js
Labels: feature

#416 Bug: Fixed and refactored the flow between Location and Questions
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Location/LocationResult.js
  apps/client/src/components/Questions.js
  apps/client/src/pages/CheckerPage.js
Labels: bug

#419 Features: Text and Styling updates from acceptance-test
  apps/client/src/components/Conclusion.js
  apps/client/src/components/ConclusionAlert.tsx
  apps/client/src/components/ConclusionAlertStyles.ts
  apps/client/src/pages/CheckerPage.js
Labels: feature

#421 Feature: updated Conclusion Alert text
  apps/client/src/components/ConclusionAlert.tsx
Labels: feature

#422 Feature: Updated page title and path
  apps/client/src/pages/CheckerPage.js
  apps/client/src/routes.js
Labels: feature

#423 Bug: Fixed ConclusionAlert styling and refactored some old code
  apps/client/src/atoms/Alert.js
  apps/client/src/components/ConclusionAlert.tsx
  apps/client/src/components/Question.js
  apps/client/src/components/QuestionAnswer.tsx
Labels: bug

#424 Feature: Added zonwering checker on chappie2.0
  apps/client/src/config/index.ts
  apps/client/src/intros/ZonweringRolluikIntroOlo.js
Labels: feature

#411 Feature: Chappie2.0 route redirects to make old URLs backwards compatible
  apps/client/src/components/Router.js
  apps/client/src/routes.js
Labels: feature

#426 Phone number refactor
  README.md
  apps/client/public/sttr/prod/dakkapel.json
  apps/client/public/sttr/prod/dakraam.json
  apps/client/public/sttr/prod/kozijn.json
  apps/client/public/sttr/prod/zonnepaneel.json
  apps/client/public/sttr/prod/zonwering.json
  apps/client/src/components/Conclusion.js
  apps/client/src/components/ContactSentence.tsx
  apps/client/src/components/Footer/Footer.js
  apps/client/src/components/Link.js
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Markdown/renderers/LinkRenderer.js
  apps/client/src/components/Markdown/renderers/LinkRenderer.tsx
  apps/client/src/components/PhoneNumber.tsx
  apps/client/src/config/matomo.js
  apps/client/src/hoc/withTracking.js
  apps/client/src/intros/DakkapelIntro.js
  apps/client/src/intros/DakraamIntro.js
  apps/client/src/intros/KozijnenIntro.js
  apps/client/src/intros/ZonweringRolluikIntro.js
  apps/client/sttr_build/index.js
Labels: feature

#434 Feedback from team: Textual updates, bug fixes and refactor
  apps/client/src/atoms/HideForPrint.js
  apps/client/src/atoms/PrintButton.js
  apps/client/src/atoms/index.js
  apps/client/src/components/Conclusion.js
  apps/client/src/components/ConclusionAlert.tsx
  apps/client/src/components/ConclusionAlertStyles.ts
  apps/client/src/components/Footer/FooterStyles.js
  apps/client/src/components/Layouts/BaseLayout.tsx
  apps/client/src/components/Location/LocationFinder.js
  apps/client/src/components/PrintDetails.js
  apps/client/src/components/QuestionAnswer.tsx
  apps/client/src/components/RegisterLookupSummary.js
  apps/client/src/pages/CheckerPage.js
Labels: feature

#436 Make text more consistent
  apps/client/src/config/index.ts
Labels: fix

#435 Feature: Disable all future questions + refactored EditButton.tsx
  apps/client/src/atoms/EditButton.tsx
  apps/client/src/atoms/EditButtonStyle.ts
  apps/client/src/components/Questions.js
Labels: feature

#420 Feature: Chappie2.0 intros
  apps/client/src/components/Conclusion.js
  apps/client/src/components/ContactSentence.tsx
  apps/client/src/config/matomo.js
  apps/client/src/intros/DakkapelIntro.js
  apps/client/src/intros/DakraamIntro.js
  apps/client/src/intros/KozijnenIntro.js
  apps/client/src/intros/ZonnepanelenIntro.js
  apps/client/src/intros/ZonweringRolluikIntro.js
  apps/client/src/intros/shared/IntroHeading.tsx
  apps/client/src/intros/shared/IntroSituationDescription.tsx
  apps/client/src/intros/shared/LocationIntro.js
  apps/client/src/intros/shared/index.js
Labels: feature

#438 Feature: Added temporary FormTitle style fix
  apps/client/src/atoms/FormTitle.tsx
  apps/client/src/atoms/index.js
  apps/client/src/components/Layouts/BaseLayout.tsx
Labels: feature

#440 Chore: PR feedback on chappie2.0
  .github/workflows/default.yml
  apps/client/src/components/DebugDecisionTable.js
  apps/client/src/components/Layouts/BaseLayout.tsx
  apps/client/src/components/Location/LocationInput.js
  apps/client/src/components/Nav.js
  apps/client/src/components/Questions.js
  apps/client/src/components/StepByStepNavigation/StepByStepItem.tsx
  apps/client/src/components/StepByStepNavigation/StepByStepNavigation.tsx
  apps/client/src/config/index.ts
  apps/client/src/pages/CheckerPage.js
  apps/client/src/routes.js
  apps/client/src/sttr_client/models/rule.js
  apps/client/src/utils/passPropsToChildren.ts
  apps/client/src/utils/usePassPropsToChildren.ts
Labels: chore
