Repository Amsterdam/vergunningcheck, pull requests merged in 2021-04, with the labels that each got.

#874 Fix deps
  package-lock.json
Labels: fix

#875 Update deps
  packages/e2e/package-lock.json
  packages/e2e/package.json
Labels: fix

#872 Bomenkap checker added
  manager/db.sqlite3
  manager/manager/settings_local.py
  packages/client/public/imtr/transformed/SCKKBFsLHGG5Le5mJ.json
  packages/client/public/imtr/transformed/X794ToraLGqGMGiT7.json
  packages/client/src/components/Outcome/OutcomeContent.tsx
  packages/client/src/components/Outcome/PermitFree.tsx
  packages/client/src/components/Question/Questions.tsx
  packages/client/src/config/index.ts
  packages/client/src/i18n/nl.ts
  packages/client/src/intros/BomenkapIntro.test.tsx
  packages/client/src/intros/BomenkapIntro.tsx
  packages/client/src/topics.json
  packages/client/src/utils/getOutcomeContent.tsx
Labels: feature

#885 Remove support for Netlify
  .gitignore
  netlify.toml
  package-lock.json
  package.json
  packages/client/.env
  packages/client/package.json
  packages/e2e/host.js
  packages/graphql/app.js
  packages/graphql/config/netlify.js
  packages/graphql/graphql.js
  packages/graphql/package.json
Labels: chore
