Repository Amsterdam/vergunningcheck, pull requests merged in 2021-02, with the labels that each got.

#792 Fixed bugs switching between checkers
  packages/client/src/components/Location/LocationSection.tsx
Labels: bug

#801 Fixed regex bug on Safari
  packages/client/src/components/Location/LocationFinder.test.tsx
  packages/client/src/utils/index.ts
Labels: bug

#805 Hotfix: reset address triggers wrong checker.next
  CHANGELOG.md
  packages/client/src/components/Question/QuestionSection.tsx
  packages/client/src/pages/CheckerPage.test.tsx
Labels: bug

#804 Updated readability of config and documentation
  CONTRIBUTING.md
  README.md
  packages/client/src/components/Location/LocationSummary.tsx
  packages/client/src/components/Outcome/DemolitionNeedReport.tsx
  packages/client/src/config/index.ts
Labels: chore

#785 Added tests and translation for Location components
  packages/client/src/__mocks__/addressMock.ts
  packages/client/src/__mocks__/addressMockNoCityScape.ts
  packages/client/src/__mocks__/addressMockNoMonument.ts
  packages/client/src/__mocks__/addressMockNoRestrictions.ts
  packages/client/src/__mocks__/addressMockNoZoningplans.ts
  packages/client/src/__mocks__/checker-autofill-only.json
  packages/client/src/components/Location/LocationSummary.test.tsx
  packages/client/src/components/Location/LocationSummary.tsx
  packages/client/src/components/Outcome/Outcome.tsx
  packages/client/src/config/autofill.test.ts
  packages/client/src/config/autofill.ts
  packages/client/src/i18n/nl.ts
  packages/client/src/pages/olo/OloLocationInput.test.tsx
  packages/client/src/pages/olo/OloLocationResult.test.tsx
  packages/client/src/types.ts
  packages/client/src/utils/index.test.tsx
  packages/client/src/utils/test-utils.tsx
Labels: chore

#813 Prevent a bug when refreshing a checker without getDataNeed
  packages/client/src/components/Question/QuestionSection.tsx
Labels: bug

#812 Improved accessibility and readability to comply with WCAG
  packages/client/src/components/Footer/Footer.tsx
  packages/client/src/components/Header.tsx
  packages/client/src/components/HeaderStyles.ts
  packages/client/src/components/Layouts/BaseLayout.tsx
  packages/client/src/components/Link.tsx
  packages/client/src/components/Location/LocationInput.tsx
  packages/client/src/components/PhoneNumber.tsx
  packages/client/src/components/StepByStepNavigation/StepByStepItem.tsx
  packages/client/src/components/StepByStepNavigation/StepByStepNavigation.tsx
  packages/client/src/intros/shared/Intro.tsx
Labels: feature

#822 Added button to Intro page and updated tests
  packages/client/src/i18n/nl.ts
  packages/client/src/intros/shared/Intro.tsx
  packages/client/src/pages/HomePage.test.tsx
  packages/client/src/pages/IntroPage.test.tsx
  packages/client/src/pages/IntroPage.tsx
  packages/client/src/pages/olo/OloLocationInput.test.tsx
  packages/client/src/pages/olo/OloLocationResult.test.tsx
Labels: feature
