Repository Amsterdam/vergunningcheck, pull requests merged in 2021-03, with the labels that each got.

#823 Husky configuration update for husky 5
  .husky/.gitignore
  .husky/pre-commit
  README.md
  package.json
Labels: chore

#829 Updated intro texts
  packages/client/src/components/ContactSentence.tsx
  packages/client/src/i18n/nl.ts
  packages/client/src/intros/ZonnepanelenIntro.tsx
  packages/client/src/intros/shared/Intro.test.tsx
  packages/client/src/intros/shared/Intro.tsx
  packages/client/src/pages/IntroPage.test.tsx
Labels: feature

#835 Updated long contact sentence
  packages/client/src/components/ContactSentence.test.tsx
  packages/client/src/components/ContactSentence.tsx
  packages/client/src/i18n/nl.ts
Labels: chore

#839 Renamed timesCheckerLoaded to timesLoaded
  packages/client/src/SessionContext.tsx
  packages/client/src/components/Location/LocationSection.tsx
  packages/client/src/components/Outcome/NewCheckerModal.tsx
  packages/client/src/components/Question/QuestionSection.tsx
  packages/client/src/pages/CheckerPage.tsx
  packages/client/src/types.ts
Labels: chore

#844 Fixed todo's and cleaned up code
  packages/client/src/components/Location/LocationInput.tsx
  packages/client/src/components/Location/LocationSummary.test.tsx
  packages/client/src/components/Outcome/NewCheckerModal.test.tsx
  packages/client/src/components/Outcome/OutcomeContent.test.tsx
  packages/client/src/components/Question/Question.tsx
  packages/client/src/i18n/nl.ts
  packages/client/src/intros/SlopenIntro.test.tsx
  packages/client/src/pages/olo/OloLocationResult.tsx
Labels: chore

#811 Updated flow when starting a new checker
  packages/client/src/components/Location/LocationSection.tsx
  packages/client/src/components/Outcome/NewCheckerModal.test.tsx
  packages/client/src/components/Outcome/NewCheckerModal.tsx
  packages/client/src/i18n/nl.ts
Labels: feature

#842 Removed inline styles
  packages/client/src/atoms/Alert.tsx
  packages/client/src/components/Location/LocationNotFound.tsx
  packages/client/src/components/Location/LocationSection.tsx
  packages/client/src/components/Outcome/OutcomeSection.tsx
  packages/client/src/components/Question/Questions.tsx
  packages/client/src/components/StepByStepNavigation/StepByStepItem.tsx
  packages/client/src/components/StepByStepNavigation/StepByStepItemStyle.ts
Labels: chore

#846 Cleaned up files and updated tests
  packages/client/package.json
  packages/client/src/components/Header.test.tsx
  packages/client/src/components/Header.tsx
  packages/client/src/components/Layouts/BaseLayout.tsx
  packages/client/src/components/Nav.test.tsx
  packages/client/src/components/Nav.tsx
  packages/client/src/components/NavStyle.ts
  packages/client/src/routes.test.ts
  packages/client/src/routes.ts
  packages/client/src/serviceWorker.ts
  packages/client/src/types.ts
  packages/client/src/utils/getOutcomeContent.test.tsx
  packages/client/src/utils/test-ids.ts
Labels: chore

#830 Added feature to render PreQuestions to checkers
  packages/client/src/SessionContext.tsx
  packages/client/src/components/Answers.test.tsx
  packages/client/src/components/Answers.tsx
  packages/client/src/components/ContactSentence.test.tsx
  packages/client/src/components/ContactSentence.tsx
  packages/client/src/components/Form.tsx
  packages/client/src/components/Outcome/OutcomeContent.tsx
  packages/client/src/components/Question/PreQuestion.test.tsx
  packages/client/src/components/Question/PreQuestion.tsx
  packages/client/src/components/Question/PreQuestionMultipleCheckers.tsx
  packages/client/src/components/Question/PreQuestions.test.tsx
  packages/client/src/components/Question/PreQuestions.tsx
  packages/client/src/components/Question/Question.tsx
  packages/client/src/components/Question/QuestionAlert.tsx
  packages/client/src/components/Question/QuestionAnswer.tsx
  packages/client/src/components/Question/Questions.tsx
  packages/client/src/config/index.ts
  packages/client/src/i18n/nl.ts
  packages/client/src/models/topic.ts
  packages/client/src/pages/CheckerPage.test.tsx
  packages/client/src/types.ts
Labels: feature

#845 Organised atoms and added documentation
  packages/client/src/atoms/AddressLines.test.tsx
  packages/client/src/atoms/AddressLines.tsx
  packages/client/src/atoms/ContactSentence.test.tsx
  packages/client/src/atoms/ContactSentence.tsx
  packages/client/src/atoms/Disclaimer.test.tsx
  packages/client/src/atoms/Disclaimer.tsx
  packages/client/src/atoms/Error.tsx
  packages/client/src/atoms/Form.test.tsx
  packages/client/src/atoms/Form.tsx
  packages/client/src/atoms/Link.test.tsx
  packages/client/src/atoms/Link.tsx
  packages/client/src/atoms/Loading.test.tsx
  packages/client/src/atoms/Loading.tsx
  packages/client/src/atoms/PhoneNumber.tsx
  packages/client/src/atoms/README.md
  packages/client/src/atoms/ScrollToTop.test.tsx
  packages/client/src/atoms/ScrollToTop.tsx
  packages/client/src/atoms/index.ts
  packages/client/src/components/Footer/Footer.tsx
  packages/client/src/components/FormStyles.ts
  packages/client/src/components/Location/LocationInput.tsx
  packages/client/src/components/Location/LocationNotFound.tsx
  packages/client/src/components/Location/LocationSummary.tsx
  packages/client/src/components/Markdown/renderers/LinkRenderer.tsx
  packages/client/src/components/Nav.test.tsx
  packages/client/src/components/Outcome/DemolitionNeedReport.tsx
  packages/client/src/components/Outcome/DemolitionPermitFree.tsx
  packages/client/src/components/Outcome/NeedPermit.tsx
  packages/client/src/components/Outcome/OutcomeContent.tsx
  packages/client/src/components/Outcome/OutcomeSection.tsx
  packages/client/src/components/Question/PreQuestion.tsx
  packages/client/src/components/Question/Question.tsx
  packages/client/src/components/Router.tsx
  packages/client/src/intros/shared/DynamicIMTRIntro.tsx
  packages/client/src/intros/shared/Intro.tsx
  packages/client/src/pages/CheckerPage.tsx
  packages/client/src/pages/ErrorPage.tsx
  packages/client/src/pages/IntroPage.tsx
  packages/client/src/pages/LoadingPage.tsx
  packages/client/src/pages/olo/OloLocationInput.tsx
  packages/client/src/pages/olo/OloLocationResult.tsx
Labels: chore

#848 Fixed bug with 'in procedure monument' addresses
  packages/client/src/__mocks__/addressMockInProcedureMonument.ts
  packages/client/src/config/autofill.test.ts
  packages/client/src/config/autofill.ts
Labels: bug

#840 Changed link hover color from red to white in error box.
  packages/client/src/atoms/Alert.tsx
  packages/client/src/utils/themeUtils.ts
Labels: bug

#841 chore: extended list of zipcodes
  docs/zipcodes.md
  packages/mocking/src/restriction.ts
Labels: chore

#857 Moved PreQuestionComponent to types
  packages/client/src/components/Question/PreQuestions.tsx
  packages/client/src/config/index.ts
  packages/client/src/models/topic.ts
  packages/client/src/types.ts
Labels: chore

#860 Fixes a small heading on mobile intro text.
  packages/client/src/intros/shared/Intro.tsx
Labels: feature

#859 Refactored Questions logic and redering
  packages/client/src/components/Question/QuestionSection.tsx
  packages/client/src/components/Question/Questions.test.tsx
  packages/client/src/components/Question/Questions.tsx
  packages/client/src/debug/DebugDecisionTable.tsx
  packages/client/src/intros/shared/DynamicIMTRIntro.test.tsx
  packages/client/src/intros/shared/DynamicIMTRIntro.tsx
  packages/imtr-client/src/models/checker.test.ts
  packages/imtr-client/src/models/checker.ts
Labels: chore

#858 Added documentation and translation
  CONTRIBUTING.md
  packages/client/src/components/Answers.tsx
  packages/client/src/components/Layouts/BaseLayout.tsx
  packages/client/src/components/Location/LocationInput.tsx
  packages/client/src/components/Location/LocationSummary.tsx
  packages/client/src/components/Nav.test.tsx
  packages/client/src/components/Nav.tsx
  packages/client/src/components/Outcome/NewCheckerModal.tsx
  packages/client/src/components/PrintDetails.tsx
  packages/client/src/components/Question/PreQuestion.tsx
  packages/client/src/components/Question/PreQuestionMultipleCheckers.tsx
  packages/client/src/components/Question/PreQuestions.tsx
  packages/client/src/components/Question/Question.tsx
  packages/client/src/config/matomo.ts
  packages/client/src/config/sentry.ts
  packages/client/src/i18n/nl.ts
  packages/client/src/models/topic.ts
  packages/client/src/pages/ErrorPage.tsx
  packages/client/src/pages/HomePage.tsx
  packages/client/src/pages/IntroPage.tsx
  packages/client/src/pages/LoadingPage.tsx
  packages/client/src/pages/NotFoundPage.tsx
  packages/client/src/pages/olo/OloLocationResult.test.tsx
  packages/client/src/types.ts
Labels: chore
